### ISSUE TITLE
Change Super shortcut to open the launcher instead of workspaces

### ISSUE THREAD

**Issue by jackpot51** [pop-os/gnome-shell-extension-pop-cosmic#10]
Also allow configuration to launch workspaces or applications

**Comment by leviport** [comment]
Does the launcher add much for mouse-focused users? I think they'd rather see the workspace view when they hit Super so they can change workspaces without having to use Ctrl+Super+{Up/L, Down/K}. Those are two-hand hotkeys on many/most keyboards, which means moving the mouse hand to the keyboard, and then back. I know remapping Super is no small task, but it might be worth investigating whether it's possible.

**Comment by ghost** [comment]
> Does the launcher add much for mouse-focused users? I think they'd rather see the workspace view when they hit Super so they can change workspaces without having to use Ctrl+Super+{Up/L, Down/K}. Those are two-hand hotkeys on many/most keyboards, which means moving the mouse hand to the keyboard, and then back. I know remapping Super is no small task, but it might be worth investigating whether it's possible.

I absolutely agree with leviport here. I appreciate the launcher and everything it does for keyboard users, but changing the core workflow like that is certainly going to impact us who mostly use super + workspaces for managing our apps and use the desktop in more traditional way (without tiling).

I suggest having both options availible, one for keyboard-centric and one for mouse-centric traditional desktop use-case.

I hope that you guys will consider it.

**Comment by jackpot51** [comment]
Implemented in https://github.com/pop-os/cosmic/commit/68bf66b37ad475e146eab9db9dec030679c651b9. I agree this will need some testing. We plan to have the super key be configurable, to support launching either the launcher, the workspaces overview, or the applications overview

**Comment by WatchMkr** [comment]
@leviport User testing and surveys have shown that hitting Super and typing an application name is the most common way to launch apps hence the reasoning to set Super to the Launcher by default for testing. We also want to strongly encourage the more efficient method of the launcher over alt/super+tab for switching apps. Super tab isn't good UX but it's been around a long time and so it's a hard behavior to change.

Launching apps does not appear to be strictly mouse vs keyboard user behavior. Nonetheless, if the mouse-driven is preferred, the default on the Super key matters less in that the mouse would be expected to be used for opening favorite apps in the dock, or Applications or Workspaces with the icons or buttons. 

![image](https://user-images.githubusercontent.com/3430283/114766115-3e536100-9d23-11eb-8b10-3295d672a310.png)

**Comment by WatchMkr** [comment]
I should add, I'm not sure workspace use is as common as we think. I've been in a few user testing sessions where the the user never had a need for workspaces. It was surprising so we hadn't thought to isolate "do you use workspaces - yes/no" to learn the actual adoption.

**Comment by leviport** [comment]
I certainly wouldn't suggest making Super -> Workspaces default, but I do still like the idea of customizeable Super key behavior. It sounds like that's the direction we're planning on taking anyway, so I'm happy.

**Comment by ids1024** [comment]
> It sounds like that's the direction we're planning on taking anyway, so I'm happy.

Indeed. Jeremy just implemented that in cosmic/desktop-widget, so it will be customizable unless we want to remove the option for some reason:

![Screenshot from 2021-04-14 12-49-24](https://user-images.githubusercontent.com/2263150/114770089-e36c3a80-9d1f-11eb-9f94-87aa40e5017a.png)

**Comment by sansubr** [comment]
> > It sounds like that's the direction we're planning on taking anyway, so I'm happy.
> 
> Indeed. Jeremy just implemented that in cosmic/desktop-widget, so it will be customizable unless we want to remove the option for some reason:
> 
> ![Screenshot from 2021-04-14 12-49-24](https://user-images.githubusercontent.com/2263150/114770089-e36c3a80-9d1f-11eb-9f94-87aa40e5017a.png)

Hey @ids1024 How do I get to this setting on Pop OS? I don't see this in the shortcuts area. I'd really like to go back to Super opening Launcher instead of Workspaces.

**Comment by alperyilmaz** [comment]
Hi, is possible to change this setting after the installation? I dont remember what I chose during installation but I want to see the Workspaces when I press Super key, now I access Applications. I didn't see Super key alone to be modified in Keyboard shortcuts menu. Is there `dconf` way or `gsettings` way to change the Super key?

**Comment by alperyilmaz** [comment]
I just found out. 

Run dconf-editor, go to `/org/gnome/shell/extensions/pop-cosmic/overlay-key-action` and select 'WORKSPACES'

**Comment by Evity** [comment]
> > > It sounds like that's the direction we're planning on taking anyway, so I'm happy.
> > 
> > 
> > Indeed. Jeremy just implemented that in cosmic/desktop-widget, so it will be customizable unless we want to remove the option for some reason:
> > ![Screenshot from 2021-04-14 12-49-24](https://user-images.githubusercontent.com/2263150/114770089-e36c3a80-9d1f-11eb-9f94-87aa40e5017a.png)
> 
> Hey @ids1024 How do I get to this setting on Pop OS? I don't see this in the shortcuts area. I'd really like to go back to Super opening Launcher instead of Workspaces.



> > > It sounds like that's the direction we're planning on taking anyway, so I'm happy.
> > 
> > 
> > Indeed. Jeremy just implemented that in cosmic/desktop-widget, so it will be customizable unless we want to remove the option for some reason:
> > ![Screenshot from 2021-04-14 12-49-24](https://user-images.githubusercontent.com/2263150/114770089-e36c3a80-9d1f-11eb-9f94-87aa40e5017a.png)
> 
> Hey @ids1024 How do I get to this setting on Pop OS? I don't see this in the shortcuts area. I'd really like to go back to Super opening Launcher instead of Workspaces.

I used to have this panel in settings (Pop!_21.04) but it corrupted since the reinstallation of pop-desktop, now it only provides a wallpaper option and the desktop panel vanished with its content which is not configurable in tweak-tools. I managed to configure the settings missing by installing Gnome extensions and dconf-editor (the resolution given by @alperyilmaz above), but I still can't find ways to get it back, hope this info helps.

**Comment by bluzky** [comment]
> > > It sounds like that's the direction we're planning on taking anyway, so I'm happy.
> > 
> > 
> > Indeed. Jeremy just implemented that in cosmic/desktop-widget, so it will be customizable unless we want to remove the option for some reason:
> > ![Screenshot from 2021-04-14 12-49-24](https://user-images.githubusercontent.com/2263150/114770089-e36c3a80-9d1f-11eb-9f94-87aa40e5017a.png)
> 
> Hey @ids1024 How do I get to this setting on Pop OS? I don't see this in the shortcuts area. I'd really like to go back to Super opening Launcher instead of Workspaces.

You can find it in Desktop settings
![Screenshot from 2021-10-19 11-25-10](https://user-images.githubusercontent.com/6194779/137843765-16f7dfe9-117e-438c-9c8f-ef4dfcb2d4e9.png)

**Comment by alperyilmaz** [comment]
Hi. It's good that there's GUI for changing the settings. However, as you see in the menu, Applications and Workspaces are **separate**. In older version, Pop!_21.04, I was pressing the Super key and I was having **both** Workspaces and Application in one screen. That was pretty convenient. With one key press I can either search for an app by start typing or click 
Now, I press Super key for Workspaces and press Super+A for applications. I wish they were not separated.

**Comment by Theluga** [comment]
Hello, I'm very new to the linux world. But I would like ask if it's possible to set super key to do nothing too.

I would like to set this key to another shortcut because I get the dash + arcmenu being called at the same time.

I just want to set it to null if it's possible, thank you very much.

**Comment by smallvalthoss** [comment]
I've been wondering for a little while if doing super + # would be good for launching applications. Where # is the position of the app you want to launch in your dock. Therefore, you can just customize the dock order of apps you use most. Then super + 1 would open your browser, 2 would open say vscode. etc.. 

Would anyone know a way of implementing this for myself??

**Comment by senntore** [comment]
> Would anyone know a way of implementing this for myself??

@smallvalthoss I think you want this(https://github.com/pop-os/cosmic-dock/issues/11#issuecomment-872501132), which can be easily achieved.

**Comment by smallvalthoss** [comment]
> > Would anyone know a way of implementing this for myself??
> 
> @smallvalthoss I think you want this([pop-os/cosmic-dock#11 (comment)](https://github.com/pop-os/cosmic-dock/issues/11#issuecomment-872501132)), which can be easily achieved.

Thank you! That helped :)
