### ISSUE TITLE
Can I install this on 20.04?  

### ISSUE THREAD

**Issue by MikeyBeez** [pop-os/gnome-shell-extension-pop-cosmic#100]
21.04 doesn't work right with my TPU; so I must stay on 20.04.  Can I clone this and install it from source on 20.04?   Will Cosmic be added to 20.04 eventually?

**Comment by ghost** [comment]
I tried. I cloned ALL the relevant packages and they kind of appeared, but nothing worked. Besides, I've seen a Pop dev say "no".

**Comment by MikeyBeez** [comment]
Thanks @derpmatt.  I may try 21.04 again to see if I can get my TPU working on it.  It's just a pain because timeshift can't restore 20.04.

**Comment by ids1024** [comment]
Extension compatibility between Gnome Shell versions can be a bit complicated, so it's not a surprise if it doesn't work on 20.04. There isn't any plan to backport it.
