### ISSUE TITLE
Launching Applications view while Workspaces view visible doesn't result in expected behavior

### ISSUE THREAD

**Issue by jhight** [pop-os/gnome-shell-extension-pop-cosmic#106]
### Steps to reproduce
1. Open Workspaces view
2. Launch Applications from the dock

### Expected result
Workspaces view is exited and Applications view is launched

### Actual result
Workspaces view is exited and Applications is not launched

**Comment by DuttaAB-dev** [comment]
Already had this covered in #65😉

**Comment by DuttaAB-dev** [comment]
> ### Steps to reproduce
> 1. Open Workspaces view
> 2. Launch Applications from the dock
> 
> ### Expected result
> Workspaces view is exited and Applications view is launched
> 
> ### Actual result
> Workspaces view is exited and Applications is not launched

 Already had this covered in #65😉

**Comment by jhight** [comment]
:+1: will close this one as a duplicate
