### ISSUE TITLE
[Feature Request] Make workspace gestures respect "natural scrolling"

### ISSUE THREAD

**Issue by fkastner** [pop-os/gnome-shell-extension-pop-cosmic#110]
Hi,
currently the gestures to switch the workspace work like this:
- swipe down: change to the workspace below, i.e. the current workspace will animate *upwards* out of view
- and vice versa

For basic scrolling there is already a toggle in the "Mouse & Touchpad" settings to use "natural scrolling", which I personally find more natural to use with a touchpad.
Maybe the gestures to change the workspace could respect that setting, too?

**Comment by jmbuhr** [comment]
While you are waiting for this to appear in the settings: The new gestures use `touchegg`: https://github.com/JoseExposito/touchegg, which can be configured by the gui application `touche`: https://github.com/JoseExposito/touche. If you swap the commands for 4-finger UP and DOWN swipes you are good to go. It might be a good idea to ship `touche` as a default application as well.

**Comment by fkastner** [comment]
Thanks for the tip. This works great for now!
I think the plan is to provide gesture controls in Settings so `touche` wouldn't really be needed?

**Comment by bartv42** [comment]
I tried this, but my settings are disabled:

![image](https://user-images.githubusercontent.com/6816469/124398537-82e50c00-dd16-11eb-95db-c60a9402893e.png)

**Comment by jmbuhr** [comment]
Very curious, maybe someone from pop-os can weigh in on why this is. For me it looks like this: 
![image](https://user-images.githubusercontent.com/17450586/124399606-aad76e00-dd1c-11eb-8f60-b191a589d9c3.png)
Might be because I installed it during the beta, so it didn't change my settings.

**Comment by fkastner** [comment]
> I tried this, but my settings are disabled:
> 
> ![image](https://user-images.githubusercontent.com/6816469/124398537-82e50c00-dd16-11eb-95db-c60a9402893e.png)

I upgraded from 20.10 and see the same thing as @jmbuhr.
Are you on Wayland, @bartv42? I think gnome can handle gestures itself on Wayland.

**Comment by DuttaAB-dev** [comment]
Yes, on wayland gnome has its own set of gestures which overrides those by touchégg. I had opened an [issue](https://github.com/pop-os/cosmic/issues/59) where sometimes there is a conflict between the default gnome gestures and those of touchégg.

**Comment by leviport** [comment]
I found a workaround that seems to work, in case anyone is interested. First, copy the default touchegg config file to your account config:
```
mkdir ~/.config/touchegg/
cp -n /usr/share/touchegg/touchegg.conf
```

Then open up that `~/.config/touchegg/touchegg.conf` file and reverse the directions for any gestures you wish to reverse. For example, to change the 4-finger swipe workspace change gesture, change 
```
    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="RUN_COMMAND">
        <repeat>false</repeat>
        <command>dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.gnome.Shell.Eval string:'let pop_cosmic = Main.extensionManager.lookup("pop-cosmic@system76.com"); if (pop_cosmic) { pop_cosmic.stateObj.gesture(pop_cosmic.stateObj.GESTURE_UP); }'</command>
        <on>begin</on>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="RUN_COMMAND">
        <repeat>false</repeat>
        <command>dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.gnome.Shell.Eval string:'let pop_cosmic = Main.extensionManager.lookup("pop-cosmic@system76.com"); if (pop_cosmic) { pop_cosmic.stateObj.gesture(pop_cosmic.stateObj.GESTURE_DOWN); }'</command>
        <on>begin</on>
      </action>
    </gesture>
```
to 
```
    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="RUN_COMMAND">
        <repeat>false</repeat>
        <command>dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.gnome.Shell.Eval string:'let pop_cosmic = Main.extensionManager.lookup("pop-cosmic@system76.com"); if (pop_cosmic) { pop_cosmic.stateObj.gesture(pop_cosmic.stateObj.GESTURE_UP); }'</command>
        <on>begin</on>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="RUN_COMMAND">
        <repeat>false</repeat>
        <command>dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.gnome.Shell.Eval string:'let pop_cosmic = Main.extensionManager.lookup("pop-cosmic@system76.com"); if (pop_cosmic) { pop_cosmic.stateObj.gesture(pop_cosmic.stateObj.GESTURE_DOWN); }'</command>
        <on>begin</on>
      </action>
    </gesture>
```

Then restart gnome-shell for changes to take effect (Alt + F2, `r`, Enter)

**Comment by fkastner** [comment]
This is fixed now with https://github.com/pop-os/cosmic/pull/320. 🎉 
For anyone who created a custom `touchegg.conf` file to fix this beforehand (either through touché or manually): that file can now be deleted or has to be modified to respect the new syntax like this https://github.com/pop-os/touchegg/pull/5/files (c.f. https://github.com/pop-os/cosmic/issues/322).
