### ISSUE TITLE
Glitchy animations when closing animations panel

### ISSUE THREAD

**Issue by eniac314** [pop-os/gnome-shell-extension-pop-cosmic#114]
I just upgraded to 21.04 from 20.10, everything seems to be working fine but I am seeing some flickering on the application icons and on the dock during the transition animations when I am closing the application panel, and when I am opening programs from the application panel.

I am also briefly seeing the desktop icons even though they should be hidden behind the opened apps. (although for some reason it does not seem to be visible in the screen-cast below)

https://user-images.githubusercontent.com/8986418/124100920-2a381980-da5f-11eb-923d-71071ad1810c.mp4

I am using a late 2012 mac mini with an Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz and integrated Intel® HD Graphics 4000 (IVB GT2).

 If I disable gnome animations with this command `gsettings set org.gnome.desktop.interface enable-animations false`, the flickering goes away.

**Comment by jmbuhr** [comment]
I can confirm this issue.

**Comment by johnvanham** [comment]
I have the same issue. Also upgraded from 21.10. Am on a Dell Inspiron 7590 which has both Intel integrated graphics as well as nvidia.


https://user-images.githubusercontent.com/1741936/125422892-edab8148-e1f2-42f2-b70c-1d123dbd26a9.mp4

**Comment by ids1024** [comment]
The animation for opening and closing Applications in the current version should be improved from what it was like when this issue was opened.

**Comment by johnvanham** [comment]
> The animation for opening and closing Applications in the current version should be improved from what it was like when this issue was opened.

I've just updated and yes it looks like this is fixed! Thank you

**Comment by eniac314** [comment]
It seems better on my system as well. The flickering is gone. I am still briefly seeing the desktop shortcuts when opening/closing the animation panel though.

**Comment by ids1024** [comment]
I haven't been able to reproduce the desktop icons issue. Since it's integrated graphics on a 2012 device and doesn't appear in the screen-cast, maybe it's somehow related to GPU drivers? Not sure how but there can be weird issues like that.

**Comment by eniac314** [comment]
I made a screencast showing the problem on the left size of the screen.

https://user-images.githubusercontent.com/8986418/126535611-0da17e36-d814-4202-8859-c0f518e9e693.mp4

I am opening and closing the applications panel with the windows key. The problems does not appear if there is no applications open on the current workspace, as the icons seem to briefly overlay on top of the opened app windows, but not on top of the app panel. 

Here is my GPU info for reference:
```
lspci -vnn | grep VGA -A 12
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Apple Inc. 3rd Gen Core processor Graphics Controller [106b:0101]
	Flags: bus master, fast devsel, latency 0, IRQ 53
	Memory at a0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at 90000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 2000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

00:14.0 USB controller [0c03]: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller [8086:1e31] (rev 04) (prog-if 30 [XHCI])
	Subsystem: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller [8086:7270]
``` 
Is there something I could try to change or upgrade the drivers?

**Comment by johnvanham** [comment]
@eniac314 which extension are you using for desktop icons? I have https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/ which looked like it was doing the same as your screencast but it just updated and appears to be fixed - the icons are not going above the windows and fade out with them instead smoothly.

**Comment by eniac314** [comment]
@johnvanham I don't remember installing any gnome extension manually, I just upgraded pop_os to 21.10 from a vanilla 20.04. Is there a way to check?

**Comment by johnvanham** [comment]
@eniac314 I don't remember if Pop!_OS came with desktop icons or not or if that's something I installed. Anyway, to see what you have you can go here: https://extensions.gnome.org/local/ It'll need to add a browser extension (I've used it on Chrome and Firefox) but you can then see what extensions you have installed and also install others.

**Comment by eniac314** [comment]
@johnvanham so apparently I had desktop-icons-ng-ding installed, I tried upgrading it, but the problem did not go away. However after removing it and installing Desktop Icons by rastersoft instead everything seems to be working fine now. 
Thank you!
