### ISSUE TITLE
Pressing super a second time should close the launcher

### ISSUE THREAD

**Issue by TLouf** [pop-os/gnome-shell-extension-pop-cosmic#115]
Hi, back in April this was planned to be implemented https://github.com/pop-os/shell/issues/929, is it still the case?

**Comment by blakeridgway** [comment]
> Hi, back in April this was planned to be implemented [pop-os/shell#929](https://github.com/pop-os/shell/issues/929), is it still the case?

I am able to confirm that this feature is added into 21.04 and assuming COSMIC in general. As spamming my Super key opens and closes the Launcher with no issues.

Reference: [pop-os/shell#927](https://github.com/pop-os/shell/pull/927)

**Comment by TLouf** [comment]
Oh well I guess that's a bug then, doesn't work on my end. I can only close the launcher with Escape. I've just upgraded from 20.10. Here's some info:
Distribution: Pop!_OS 21.04
Gnome shell version: 3.38.5
Pop shell version: 1.1.0\~1625266132~21.04\~78833ad
Let me know if you need any more info from my side.
