### ISSUE TITLE
Cosmic missing Cosmic settings

### ISSUE THREAD

**Issue by HadiHassan22** [pop-os/gnome-shell-extension-pop-cosmic#119]
It seems like somehow the update got corrupted on my machine. It all seems to be fine and I have the dock at the bottom. However, when I came to customize the new dock, I realized I am not able to because the desktop tab in settings is not there!

In the pop shop it also says there are operating system updates however when i try to update them I get the following: 

Failed to update “Operating System Updates”
This may have been caused by external or manually compiled software.

```
The following packages have unmet dependencies:
  libmutter-7-0: Depends: libc6 (>= 2.33) but 2.32-0ubuntu3 is to be installed
                 Depends: libegl1 but it is not going to be installed
                 Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) but it is not installable
                 Depends: libgl1 but it is not going to be installed
                 Depends: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is to be installed
  systemd-sysv: Depends: systemd (= 247.3-3ubuntu3.1pop1~1623176805~21.04~74cb00e)
  fwupd: Depends: libc6 (>= 2.33) but 2.32-0ubuntu3 is to be installed
         Depends: libfwupdplugin1 (>= 1.5.8-0ubuntu1pop0~1617221312~21.04~a9de48d) but 1.5.8-0ubuntu1pop0~1617221312~20.10~a9de48d is to be installed
         Depends: libgnutls30 (>= 3.7.0) but 3.6.15-4ubuntu2 is to be installed
         Depends: libgusb2 (>= 0.3.5) but 0.3.4-0.2 is to be installed
         Depends: libtss2-esys-3.0.2-0 (>= 2.3.1) but it is not installable
  linux-headers-5.11.0-7620-generic: Depends: libc6 (>= 2.33) but 2.32-0ubuntu3 is to be installed
  gnome-terminal: Depends: libvte-2.91-0 (>= 0.62.1) but 0.62.0-1ubuntu1 is to be installed
                  Recommends: yelp but it is not going to be installed
```

It's almost as if the settings app and some other components are still in the 20.10 version and the os is on 21.4. I tried doing a refresh install with a new copy of the iso but that also did not work, from the logs if im not mistaken it was a problem that came up while doing grub-install. any help would be appreciated

**Comment by DuttaAB-dev** [comment]
Try checking your repos in `/etc/apt/sources.list.d/` if each and every mention of "groovy" in each repo file has been replaced with "hirsute".

Similar to #37 #78

**Comment by HadiHassan22** [comment]
No they have not these are the repos in `/etc/apt/sources.list.d/`
`docker.list                     mssql-release.list             pop-os-ppa.list                  system.sources
google-chrome.list              ondrej-ubuntu-php-groovy.list  slack.list                       teamviewer.list
mixxx-ubuntu-mixxx-groovy.list  pop-os-apps.sources            system76-ubuntu-pop-groovy.list
`

I tried running `sudo apt update && sudo apt upgrade` and this was the output:

```
Hit:1 http://ppa.launchpad.net/mixxx/mixxx/ubuntu groovy InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                 
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease                                                                            
Hit:4 https://download.docker.com/linux/ubuntu groovy InRelease                                                                              
Hit:5 https://linux.teamviewer.com/deb stable InRelease                                                                                      
Hit:6 http://us.archive.ubuntu.com/ubuntu groovy InRelease                                                                                   
Hit:7 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease                                                                         
Hit:8 https://packages.microsoft.com/ubuntu/20.10/prod groovy InRelease                                                                      
Hit:9 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease                                                                      
Hit:10 http://apt.pop-os.org/proprietary groovy InRelease                                                          
Hit:11 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease                         
Hit:12 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease                          
Hit:13 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease  
Hit:14 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
58 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  fwupd-signed gir1.2-flatpak-1.0 gir1.2-gdm-1.0 gir1.2-mutter-7 gnome-settings-daemon-common gnome-shell-common gnome-shell-extension-prefs
  libglapi-mesa libglapi-mesa:i386 libnss-systemd linux-headers-generic nautilus-extension-gnome-terminal systemd-sysv
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
```
I also tried to upgrade gnome-settings-daemon-common manually and this was the output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-settings-daemon : Depends: gnome-settings-daemon-common (= 3.38.0-1ubuntu1pop0~1600884218~20.10~971327c) but 3.38.1-3ubuntu3pop0~1616443914~21.04~e0d6dcd is to be installed
E: Broken packages
```

**Comment by DuttaAB-dev** [comment]
> No they have not these are the repos in `/etc/apt/sources.list.d/`
> `docker.list mssql-release.list pop-os-ppa.list system.sources google-chrome.list ondrej-ubuntu-php-groovy.list slack.list teamviewer.list mixxx-ubuntu-mixxx-groovy.list pop-os-apps.sources system76-ubuntu-pop-groovy.list `
> 
> I tried running `sudo apt update && sudo apt upgrade` and this was the output:
> 
> ```
> Hit:1 http://ppa.launchpad.net/mixxx/mixxx/ubuntu groovy InRelease
> Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                 
> Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease                                                                            
> Hit:4 https://download.docker.com/linux/ubuntu groovy InRelease                                                                              
> Hit:5 https://linux.teamviewer.com/deb stable InRelease                                                                                      
> Hit:6 http://us.archive.ubuntu.com/ubuntu groovy InRelease                                                                                   
> Hit:7 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease                                                                         
> Hit:8 https://packages.microsoft.com/ubuntu/20.10/prod groovy InRelease                                                                      
> Hit:9 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease                                                                      
> Hit:10 http://apt.pop-os.org/proprietary groovy InRelease                                                          
> Hit:11 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease                         
> Hit:12 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease                          
> Hit:13 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease  
> Hit:14 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 58 packages can be upgraded. Run 'apt list --upgradable' to see them.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages have been kept back:
>   fwupd-signed gir1.2-flatpak-1.0 gir1.2-gdm-1.0 gir1.2-mutter-7 gnome-settings-daemon-common gnome-shell-common gnome-shell-extension-prefs
>   libglapi-mesa libglapi-mesa:i386 libnss-systemd linux-headers-generic nautilus-extension-gnome-terminal systemd-sysv
> 0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
> ```
> 
> I also tried to upgrade gnome-settings-daemon-common manually and this was the output:
> 
> ```
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  gnome-settings-daemon : Depends: gnome-settings-daemon-common (= 3.38.0-1ubuntu1pop0~1600884218~20.10~971327c) but 3.38.1-3ubuntu3pop0~1616443914~21.04~e0d6dcd is to be installed
> E: Broken packages
> ```

your repo is full of groovy stuff. It seems like pop upgrade failed to upgrade the repos again. You can try the fix I provided in #37, that is replacing the occurrence of "groovy" with "hirsute" in each repo file. After that, try the update commands again. Hopefully this will work.

Also, @jacobgkau, I think you guys have another similar case in here.

**Comment by HadiHassan22** [comment]
so i just rename the files and it should work? also I apologize I thought the fix you mentioned was just to run apt update and upgrade.

**Comment by DuttaAB-dev** [comment]
> so i just rename the files and it should work? also I apologize I thought the fix you mentioned was just to run apt update and upgrade.

not just rename the files, but also the contents. 
for example, taking the `system.sources` file,

Before :-
```
X-Repolib-Name: Pop_OS System Sources
Enabled: yes
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: groovy groovy-security groovy-updates groovy-backports
Components: main restricted universe multiverse
X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu/
```
After:-
```
X-Repolib-Name: Pop_OS System Sources
Enabled: yes
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: hirsute hirsute-security hirsute-updates hirsute-backports
Components: main restricted universe multiverse
X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu/
```

This is supposed to be done automatically by the pop-upgrade utility, but sometimes it fails in doing so, as in your case.

**Comment by HadiHassan22** [comment]
Is there a command or maybe a guide somewhere on how to do this? I'm worried I do these changes by force and end up messing something up. But if it is strictly just the filename and the mentions of groovy in those files in `/etc/apt/sources.list.d` then I can do it by hand. Otherwise I guess I could try using the zip you shared in #78

**Comment by DuttaAB-dev** [comment]
Yes, you may try doing that, just replace the system sources with the ones present in that zip.

**Comment by DuttaAB-dev** [comment]
If that does not work, please do provide me with a list of all the files that you have in your `sources.list.d` folder, so that I can suggest possible fixes.

**Comment by DuttaAB-dev** [comment]
> Is there a command or maybe a guide somewhere on how to do this? I'm worried I do these changes by force and end up messing something up. But if it is strictly just the filename and the mentions of groovy in those files in `/etc/apt/sources.list.d` then I can do it by hand. Otherwise I guess I could try using the zip you shared in #78

And yeah, doing them by hand wont break anything until you run the command `sudo apt upgrade`, even if you mess things up. I myself faced this issue while upgrading and thus came up with this fix while experimenting and this fix has been working ever since. Just make sure to follow the instructions exactly as I say. Hope this helps!

**Comment by HadiHassan22** [comment]
Your solution worked perfectly thank you so much for the help

**Comment by DuttaAB-dev** [comment]
Glad that it worked! But I dont think you should close this issue just yet, rather you should rename it to something like "Pop-upgrade fails to upgrade distro-repos." As this issue is very much active and there no solution as of yet. The devs are still investigating the cause.
