### ISSUE TITLE
Applications Views search not responsive after installing new program

### ISSUE THREAD

**Issue by tngebauer** [pop-os/gnome-shell-extension-pop-cosmic#120]
For my install of Cosmic, a weird behavior occurs. 
After a fresh install, opening the Application View and typing right away pipes the input directly into the search, and everything works as intended. 
Then, after installing any program, the next time the Application View is opened, the search is not focused. 
To use the search again, it has to be clicked. 
Further, any other keyboard input interactions are ignored as well (like pressing Escape to close the Applications View).

It seems to be a COSMIC problem because after disabling the COSMIC extension, the search in the Application View again works as intended.

**Comment by DuttaAB-dev** [comment]
> For my install of Cosmic, a weird behavior occurs.
> After a fresh installing, opening the Application View and typing right away pipes the input directly into the search, and everything works as intended.
> Then, after installing any program, the next time the Application View is opened, the search is not focused.
> To use the search again, it has to be clicked.
> Further, any other keyboard input interactions are ignored as well (like pressing Escape to close the Applications View).
> 
> It seems to be a COSMIC problem because after disabling the COSMIC extension, the search in the Application View again works as intended.

Facing the same issue after updating cosmic today to its latest release. Never experienced this issue in the previous releases.

**Comment by Metal-spoon** [comment]
Same issue after latest update, doesn't seem to focus the search bar.
Have to click it myself.

**Comment by DuttaAB-dev** [comment]
This issue has been fixed by today's update.

**Comment by tngebauer** [comment]
Indeed, the bug was fixed with today's update :)
Issue closed!
