### ISSUE TITLE
Weird issue when trying to open the workspaces view using the hot-corner.

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#125]
Faced a weird issue today, where when I activated the workspaces view using the hot-corner, all the windows, the dock, the desktop icons and the workspaces picker got hidden somewhere.
![Screenshot from 2021-07-04 22-08-04](https://user-images.githubusercontent.com/61903332/124393822-fa686a80-dd19-11eb-8140-d038386b0c8d.png)

For reference, this below is my desktop layout 
![Screenshot from 2021-07-04 22-50-28](https://user-images.githubusercontent.com/61903332/124393879-474c4100-dd1a-11eb-9e7f-345037c57faf.png)

When I was struck to that view, opening the settings from the gnome context menu seemed to be opening the app, yet nothing was being displayed. In fact, the first screen shot was taken just after doing that. Same with telegram when I clicked on the open telegram button from its appindicator.

Only after I logged out and then logged back in that everything was normal again.

**Comment by DuttaAB-dev** [comment]
Now given that my desktop name was hidden in the top bar when that happened(which is only hidden when I am in the workspaces view as it is being shown by the Unite extension) I think it was stuck in the workspaces view

**Comment by Samaritanl** [comment]
I just posted something similar that happens when i launch Steam. Super annoying.

**Comment by DuttaAB-dev** [comment]
Fixed in the latest update
