### ISSUE TITLE
Launcher units in conversion

### ISSUE THREAD

**Issue by TC68** [pop-os/gnome-shell-extension-pop-cosmic#128]
The units provided for the answer to a unit conversion using the launcher appear incorrect.

If I bring up the launcher and type

=10kg lb

I get the answer

22.046226218487757 lb^2

The numbers are correct, but the units for the answer appear to be "lb^2" or "pounds squared", which seems incorrect. I would have expected just "lb". The "^2" appears for other conversions as well.

**Comment by mmstick** [comment]
The correct query would be `= 10 kg in lb`, but these outputs are controlled entirely by Math.js rather than this extension.

**Comment by TC68** [comment]
thanks

**Comment by TC68** [comment]
all sorted - I might just need to research the commands some more
