### ISSUE TITLE
Disabled Dock shows up in Workspaces and Applications views

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell-extension-pop-cosmic#13]
Shouldn't show up anywhere.

**Comment by jackpot51** [comment]
If this is about the "Show Dock on the Desktop" toggle, that is meant only to enable/disable the dock outside the overviews. The workspaces and applications overviews are expected to still show the dock like GNOME does prior to COSMIC.

If we want a way to disable it entirely, I believe that needs to be another toggle

**Comment by WatchMkr** [comment]
We don't have a dash concept in COSMIC. How about we rename "Show Dock on the Desktop" to "Show Dock"?

**Comment by jackpot51** [comment]
Sure, that can be done

**Comment by jackpot51** [comment]
This is addressed in https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/commit/23ac7a57994653d7fa9f6127eb136b62b404e861 and https://github.com/pop-os/desktop-widget/commit/480501d550129b9a10504854543e75b62c6276e3
