### ISSUE TITLE
Issue while updating the operating system via the pop_shop

### ISSUE THREAD

**Issue by ahmed-besic** [pop-os/gnome-shell-extension-pop-cosmic#133]
When I try to update the operating system it shows me this error:

Failed to update “Operating System Updates”
This may have been caused by external or manually compiled software.

The following packages have unmet dependencies:
gnome-shell-extension-cosmic-dock: Breaks: gnome-shell-extension-ubuntu-dock but 69ubuntu1pop0~1624393749~21.04~00aed10 is to be installed

What can I do to fix the issue?

**Comment by malangston** [comment]
I saw this a few days ago, running the following fixed it for me: sudo apt full-upgrade

**Comment by ahmed-besic** [comment]
Thank you, this fixed the issue!
