### ISSUE TITLE
COSMIC breaks Clock/Date Menu when using an alternative to COSMIC Dock

### ISSUE THREAD

**Issue by tngebauer** [pop-os/gnome-shell-extension-pop-cosmic#134]
When using an alternative to the COSMIC Dock like [Dash2Panel](https://github.com/home-sweet-gnome/dash-to-panel), COSMIC overwrites the clocks position and thereby breaks the Panel. 
The clock button returns after re/enabling the Dash2Panel extension again or disabling COSMIC. 

Of course it can not be expected, that the compatibility to all gnome extensions is guaranteed, but maybe to some of the bigger once that can enhance the user experience :)

**Screenshots:**
Problem caused by COSMIC:
![Screenshot from 2021-07-05 21-48-15](https://user-images.githubusercontent.com/21181110/124515397-a7f18180-dddf-11eb-8729-6a2d0d9cb554.png)
Expected behaviour and after re/enabling Dash2Panel: 
![Screenshot from 2021-07-05 21-48-40](https://user-images.githubusercontent.com/21181110/124515405-ac1d9f00-dddf-11eb-84d1-714aefdd2a55.png)

**Comment by jmbuhr** [comment]
Interestingly, this can temporarily be fixed by disabling and re-enabling the dash to dock extension. Additionally, this makes the hot-corners work for me again. But this only works until the next reboot or shell reload.

**Comment by tngebauer** [comment]
> Interestingly, this can temporarily be fixed by disabling and re-enabling the dash to dock extension. Additionally, this makes the hot-corners work for me again. But this only works until the next reboot or shell reload.

Yes, after a little digging I found that this has most likely to do with COSMICs clock alignment method, which  overwrites the position of the clock resulting in the empty space. Re-enabling the extension overwrites the position once again to the intended position. 

When you reboot/reload the shell, COSMICs clock alignment method is called again breaking the position again.

My linked pull request temporary fixes this problem, but only for the dash to panel extension (definitely not beautiful, but works™).

**Comment by jmbuhr** [comment]
Maybe a more general fix would be to load cosmic before other extensions, so that it doesn't override those settings.

**Comment by tngebauer** [comment]
Definitely, maybe the devs have some spare time soon to look into this.

**Comment by ids1024** [comment]
> Maybe a more general fix would be to load cosmic before other extensions, so that it doesn't override those settings.

I'm not sure there's a good way to enforce Gnome Shell extension load order like this. It would also be messed up again if a user tries to change the clock alignment in Settings, which would cause the code to be run again.

I guess something like what https://github.com/pop-os/cosmic/pull/135 adds is probably better than nothing. But I'm not sure there's a good general solution. It's kind of the nature of Gnome Shell extensions that extensions trying to do non-trivial things may conflict in various ways.
