### ISSUE TITLE
Visual glitch in the Activities overview and the Apps menu after disabling the pop-cosmic extension.

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#139]
For reference, here's the issue in action.

Activities overview:-

https://user-images.githubusercontent.com/61903332/124571649-9c489e00-de65-11eb-80ea-921465ca3ece.mp4

All Apps Menu:-

https://user-images.githubusercontent.com/61903332/124571723-b08c9b00-de65-11eb-9f56-efed1d5432b1.mp4

One thing to note tho, I am using the Wayland session, with all the latest updates installed and haven't tested this yet in X11

**Comment by DuttaAB-dev** [comment]
Both these issues disappear after a reboot/restart of the gnome shell, though the show applications button in the dock does not work anymore.
Also, the workspaces picker is not available, unless the user manually switches to a new workspacess using either the keyboard shortcut or the trackpad gesture.
![Screenshot from 2021-07-06 14-37-43](https://user-images.githubusercontent.com/61903332/124574105-c69b5b00-de67-11eb-9af9-8c805389af2b.png)
![Screenshot from 2021-07-06 14-37-48](https://user-images.githubusercontent.com/61903332/124574130-cdc26900-de67-11eb-840b-5b0ddabaccd7.png)

**Comment by Kartonrealista** [comment]
Press alt+f2, type r and press enter. This resets the Gnome shell. Some extensions need the shell to be reset to work or be fully disabled. I could only reproduce this bug once, after that I could freely change between COSMIC and default Gnome.

If you're asking why the workspace picker and show applications button don't work it's probably because they are meant with COSMIC in mind and open Workspaces view (which doesn't exist in Gnome in it's COSMIC form) and Applications view (which is implemented differently and in default Gnome is an overlay with an animation of apps popping into place instead of a black screen with static apps). To get back access to Show Applications functionality **disable the extentsion Cosmic Dock** and remove the colorful icon with 9 squares from favorites.

**Comment by DuttaAB-dev** [comment]
> Press alt+f2, type r and press enter. This resets the Gnome shell. Some extensions need the shell to be reset to work or be fully disabled. I could only reproduce this bug once, after that I could freely change between COSMIC and default Gnome.

I know, but this is not possible in wayland, which is the default in my case.

**Comment by Kartonrealista** [comment]
From StackExchange:
>Under Wayland, gnome-shell does not have a graceful way to restart and leave the applications open. If you must restart gnome-shell then you are probably better off saving all of your work and using the menu to log out. If that's not working for some reason, the command killall -HUP gnome-shell will get it done from the command runner (Alt+F2) or terminal.

Maybe logging out is a good option. You don't have to reboot the whole computer then

**Comment by DuttaAB-dev** [comment]
> Maybe logging out is a good option. You don't have to reboot the whole computer then

Well rebooting the system also reboots the shell so it means the same anyways. 

> If you're asking why the workspace picker and show applications button don't work it's probably because they are meant with COSMIC in mind and open Workspaces view

But my point here is, after disabling the cosmic shell, the workspaces picker should revert back to the default gnome behaviour as this is not something developed by the pop_os devs that it should depend on the cosmic extension in any way with it disabled. They are just using the cosmic extension to re purpose it and make it more customisable.

 > Applications view (which is implemented differently and in default Gnome is an overlay with an animation of apps popping into place instead of a black screen with static apps). To get back access to Show Applications functionality disable the extentsion Cosmic Dock and remove the colorful icon with 9 squares from favorites.

And this implementation causes issues such as #65. Thus again my point here is to make slight changes to the show apps button  so that it is no longer dependent on the cosmic extenson and/or the current location in the shell(if that makes sense.)

(PS: I might be wrong at a lot of things here so please do correct me if I got it wrong somewhare)

**Comment by Kartonrealista** [comment]
>But my point here is, after disabling the cosmic shell, the workspaces picker should revert back to the default gnome behaviour 

I misunderstood what you were saying here, nevermind

**Comment by ids1024** [comment]
> Also, the workspaces picker is not available, unless the user manually switches to a new workspacess using either the keyboard shortcut or the trackpad gesture.

This is just the stock Gnome behavior, right? I see this behavior when disabling the extension, and it continues to work that way on restarting the shell. So as far as I can tell that's all working as expected.

**Comment by DuttaAB-dev** [comment]
> This is just the stock Gnome behavior, right? 

@ids1024 No it isn't. By default, the workspaces picker is always available even when no other workspaces are being used, though the picker is halfway tucked to the right side and it fully revealed when the mouse hovers over it. Pop os had previously changed this behaviour to make the picker be fully visible all the time.

For example, here are some reference screen shots from fedora 33 using gnome 3.38.

![Screenshot from 2021-07-09 11-03-28](https://user-images.githubusercontent.com/61903332/125028780-3bf46f00-e0a6-11eb-961a-1f3cfcdab1be.png)
[The default behaviour]

![Screenshot from 2021-07-09 11-05-44](https://user-images.githubusercontent.com/61903332/125028828-4e6ea880-e0a6-11eb-9c29-046abc692f0e.png)
[Picker fully revealed when hovered over with the mouse pointer]
