### ISSUE TITLE
Hot-Corner not working on primary display

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/gnome-shell-extension-pop-cosmic#144]
When the hot-corner is enabled via pop-desktop settings, it only works in the leftmost corner of the leftmost screen. Disabling and re-enabling the hot-corner via either gnome tweak tools or dash-to-dock makes the hot-corner available on the primary display as well. But after a reboot or shell reload, the pop-deskop settings appear to take over again.

**Comment by ids1024** [comment]
> Disabling and re-enabling the hot-corner via either gnome tweak tools 

It's strange if the hot corner settting to Gnome Tweaks has different results from Pop's Deskop settings. Both should just toggle on an off the `enable-hot-corners` gsetting in `org.gnome.desktop.interface`...

**Comment by jmbuhr** [comment]
I am also very confused. Currently, I don't have my second monitor, and I was not able to find any difference except that dash-to-panel has a dconf setting of `stockgs-force-hotcorner=false` to force the hot-corner on the primary display, which was indeed not touched by pop-settings. I will see if I can reproduce this once I am back on my additional monitor.

**Comment by jmbuhr** [comment]
Closing this here. It is most definitely not related to `cosmic` but rather to `dash-to-panel`
