### ISSUE TITLE
Files and folders not found by launcher,

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/gnome-shell-extension-pop-cosmic#146]
but file search is removed from the old gnome search in the applications overview. There are almost no folders and files that are reliably found using either the `d:` or `files` keyword in the launcher.

This is especially annoying for files that serve as entry points to workspaces or projects for certain applications, be it VS Code Workspaces or RStudio projects to name just two. I don't want to have to open up the folder in nautilus just to launch a project, which previously worked flawlessly with gnome search. If the old gnome search functionality has to be removed, why not integrate those search providers into the launcher (preferably before removing the functionality from gnome search, leaving us in a limbo)?

As a reproducible example, simply run
`cd ~` followed by `mkdir test` and then try to find the folder `test` with the launcher. Nautilus and conversely also gnome search via the nautilus search provider find it without problems.

**Comment by mmstick** [comment]
I think you mean `recent` rather than `d:`, and `file` rather than `files`. As long as the project is located in your home directory, and is not contained within an ignore file, it should be accessible to fdfind (`file`).

**Comment by jmbuhr** [comment]
Right, my bad, that was a typo in the issue. Both commands are not able to find this test-folder in my home directory. Whereas if I go through `dconf` and re-enable nautilus search for the applications search it is found:

![image](https://user-images.githubusercontent.com/17450586/124976727-ee3d1f80-e02f-11eb-986b-d814581583db.png)

**Comment by jmbuhr** [comment]
Oh, hang on a second. Does `ignore file` also mean something like `gitignore`?

**Comment by jmbuhr** [comment]
Ohhhh, it looks like it does! I have to apologize for complaining so loudly.

This was way harder to foresee than I expected. As it happens, I put my dotfiles in the home directory under version control and used a `.gitignore` file to make sure only those dotfiles will be recorded.

**Comment by jmbuhr** [comment]
I leave this issue open for now, so you can decide if you consider ignoring files for git to be the same as ignoring files for the launcher search, and in case anyone else stumbles on this. But I apologize for misdirecting my annoyance!

**Comment by mmstick** [comment]
Yes, fdfind does ignore gitignore definitions by default, because you generally don't want gitignore'd files being recursed, as they're most often noise.

**Comment by jmbuhr** [comment]
Makes sense, thanks! I guess the edge cases where you would want files ignored by git to be found by a system wide search are outweight by the benefits.
