### ISSUE TITLE
Request for basic features that vanilla GNOME doesn't want to implement

### ISSUE THREAD

**Issue by articpinecone** [pop-os/gnome-shell-extension-pop-cosmic#15]
Please implement support for thumbnails in the file browser and a hibernation button in the power menu.

**Comment by jackpot51** [comment]
Both of these are out of scope of this project

**Comment by arvigeus** [comment]
Don't want to open a new issue because probably would be closed too, but is dynamic transparent panel like elementary OS out of scope too?

**Comment by jackpot51** [comment]
Can you give some more information about what that is?

**Comment by articpinecone** [comment]
Could you please elaborate on why implementing those features would be out of the scope of this project? I was under the impression that cosmic was a fork of the GNOME desktop environment designed to address complaints that people have about GNOME, such as the refusal to add features that other desktop environments/operating systems have had for a few decades.

**Comment by jackpot51** [comment]
COSMIC is an extension of *GNOME Shell*, not every single GNOME project. When you mention thumbnails in the file browser, that is nautilus, not something we have forked. Hibernation requires a ton of work across the OS, again, not just adding a button in GNOME Shell.

**Comment by roracle** [comment]
> Can you give some more information about what that is?

Dynamic transparency, meaning the panel has transparency features which shift. The shift is dictated by the wallpaper color.

Personal opinion: I really don't like the solid colors of Gnome shell. Giving people control over translucency, and even implementing it by default, makes it look appealing. It's little overhead.

**Comment by philibertc** [comment]
> hibernation button in the power menu.

@DanBaur 
Hello,
There are plenty of tutorials explaining how to do it. The button is added automatically when the hibernation is activated I believe.
