### ISSUE TITLE
Recent Update Creating/Showing Blank .desktop files

### ISSUE THREAD

**Issue by YachaywasiAI** [pop-os/gnome-shell-extension-pop-cosmic#158]
After applying some updates in 21.04 today, I noticed that it had created a bunch of blank icons for Appearance, Dock, Cosmic, Workspaces, and Desktop in the Applications menu. 

![Screenshot from 2021-07-15 16-07-03](https://user-images.githubusercontent.com/81394405/125858392-badacd8e-28e8-41cb-82d0-bb3061b48ddf.png)

**Comment by mmstick** [comment]
Already fixed
