### ISSUE TITLE
Unexpected behaviour with "Show Applications" icon in dock.

### ISSUE THREAD

**Issue by Zacxen** [pop-os/gnome-shell-extension-pop-cosmic#164]
When the workspaces view is open and you click on "Show Applications", workspaces view gets closed and you go back to the desktop. It is the same behaviour you would expect by clicking on "Show Applications" while already in applications.

Here is how I can reproduce it:
- Activate "Show Applications Icon in Dock" option under settings
- Open workspaces view and click on "Show Applications" in the dock.
-  Applications will not open and instead you will return to desktop.

Expected behaviour is that it would show applications.

**Comment by DuttaAB-dev** [comment]
duplicate of #65

**Comment by Zacxen** [comment]
I missed that issue when looking to see if it had been reported already. Will close this one as a duplicate.
