### ISSUE TITLE
Option to have the super key do nothing

### ISSUE THREAD

**Issue by jmaargh** [pop-os/gnome-shell-extension-pop-cosmic#169]
Currently, we are given three options for the action of the super key (which actually means `overlay-key` in gnome):
1. Launcher
2. Workspaces
3. Applications

It would be nice if there were an option to simply not have pop cosmic react to the super key at all. This is useful if, like me, you have other extensions you want to use the super key, or if you simply don't want that key to have any of the given actions. Of course, another option would be to be able to configure the this pop os "action" key to something other than gnome's `overlay-key`, bu tlooking at the code that would be much more work.

I'm happy to contribute if this has any appeal.

Right now I've manually replaced the `overview_toggle` function with a no-op, but it's not exactly elegant.

**Comment by ids1024** [comment]
> Right now I've manually replaced the overview_toggle function with a no-op, but it's not exactly elegant.

Another solution for that would be to set the `/org/gnome/mutter/overlay-key` dconf setting to an empty string, disabling the binding.

I suppose that doesn't work for you since some other extension is dependent on it?

**Comment by jmaargh** [comment]
> I suppose that doesn't work for you since some other extension is dependent on it?

Precisely. I would also argue that since `overlay-key` is a gnome setting, not a pop one, it is inappropriate for any extension to monopolise it unconditionally.

**Comment by jmaargh** [comment]
Went ahead and made a PR for this change. I'm hopeful for merging because it's very simple and adds minimal complexity.
