### ISSUE TITLE
topbar active application button does not appear

### ISSUE THREAD

**Issue by dyansilva** [pop-os/gnome-shell-extension-pop-cosmic#181]
The title bar button when an application is open is not showing. I've tried to make it appear by dconf but I wasn't successful. Only with the Multi Monitors Add-On extension and with two monitors it appears.
the button is this.
![image](https://user-images.githubusercontent.com/32774948/127918604-b41b03e4-58f7-4837-aa8b-4b9cc41cdd5e.png)

**Comment by ids1024** [comment]
This is intentionally disabled by the Cosmic extension, and there isn't currently a dconf setting to re-enable it. Though perhaps a setting could be added.

**Comment by dyansilva** [comment]
It would be great to have this configuration

**Comment by j3lamp** [comment]
I would appreciate a way to access the application menu. In some cases there appears to be functionality in the application menu that can't be accessed elsewhere. For example, in Geary there was an item in the application menu to open a new main window, but I haven't found how to do that without said menu.

[ I have been very happy with Pop!OS and overall am enjoying 21.04. ]

**Comment by dyansilva** [comment]
I use app-menu-bar to make the top bar that way. Of course I also use the app-menu-bar features.
![image](https://user-images.githubusercontent.com/32774948/129463253-3c311b51-45b0-402c-9110-22b5abed6b20.png)

**Comment by ids1024** [comment]
> For example, in Geary there was an item in the application menu to open a new main window, but I haven't found how to do that without said menu.

Arguably it's a bug if some things are only available in the app menu, supposing the App cares about support for non-Gnome environments. Though in that case it looks like right clicking on the app's icon in the dock or in the applications screen has a "New Window" option.

According to [this blog post](https://blogs.gnome.org/aday/2018/10/09/farewell-application-menus/) removing the app menu was planned in upstream Gnome as of 2018. Not sure if that's changed or if it's blocked by something.

**Comment by j3lamp** [comment]
Ah! Thanks @ids1024, for the workaround. I think that was the only App Menu I really used anyway.
