### ISSUE TITLE
Human interface guidelines (HIG) guide for Cosmic / Pop_OS!

### ISSUE THREAD

**Issue by chadradams** [pop-os/gnome-shell-extension-pop-cosmic#188]
## Request
As a application designer/developer.  
I need a strong reference design guide with design assets,
So that I can design and develop high quality applications for Pop_OS! and Cosmic based desktop apps.

## Expected output
- [ ] Digital assets for designing Linux apps with Cosmic in mind.
- [ ] Assets must be Linux friendly (so Figma, InVision, Marvel, UXPin, Krita, GIMP, etc).  TBD by product team.
- [ ] Hosted site with content for the HIG, (either on System 76, or in GitHub).  Similar to [https://developer.gnome.org/hig/](https://developer.gnome.org/hig/)

**Comment by mmstick** [comment]
it's the same as for GNOME

**Comment by chadradams** [comment]
Closing, thanks.
