### ISSUE TITLE
Desktop > General > Add Hot Corner settings

### ISSUE THREAD

**Issue by jackpot51** [pop-os/gnome-shell-extension-pop-cosmic#2]

**Comment by Sheenomatics** [comment]
May I kindly ask where this functionality is? I tried using the hot corner after installing PopOs Cosmic Alpha 24.04 and neither do I find the setting nor does the hot corner Work. This was one of the main reasons I loved PopOs so much. Can you please check?

**Comment by leviport** [comment]
@Sheenomatics This repo is not for COSMIC DE. Hot corners for COSMIC DE is being tracked here: https://github.com/pop-os/cosmic-epoch/issues/667
