### ISSUE TITLE
Super Key behavior reverts to showing Workspaces without changing any options 

### ISSUE THREAD

**Issue by ghost** [pop-os/gnome-shell-extension-pop-cosmic#200]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Launcher

**Issue/Bug Description:**
The default behavior for the Super key is to open the **Launcher**. However, sometimes it will change (for no discernible reason) to showing the **Workspaces** screen.

![Screenshot from 2021-08-25 07-18-30](https://user-images.githubusercontent.com/60396877/130789221-ceef04ba-d752-406a-a06e-b1ef7786f25a.png)
Opening Settings > Desktop > General shows that **Launcher** is still the selected option. Attempting to reset things by setting it to **Workspaces** then setting it back to **Launcher** does not resolve the issue.

At one point there was an option in Tweak app > Extensions > Pop cosmic > _gear_ that could fix it. I was able to do something with the Super key in there (I don't remember what) but that option is no longer available. Now I just have to log out then log back in.

**Steps to reproduce (if you know):**
I don't know (yet) what incites the change, but I'll keep track as best I can and edit if I figure it out.

**Expected behavior:**
Super key should always display Launcher (if that's what your setting is) and not change to showing Workspaces.

**Other Notes:**
I guess there's a chance that this is intended functionality -- like, maybe it's supposed to show **Workspaces** if you have more than one window open. If that's the case, the setting description should be clearer, and perhaps there should be an option to force the Launcher (or, again, whichever option you choose in Settings > Desktop > General) every time.

**Comment by jacobgkau** [comment]
> I guess there's a chance that this is intended functionality

This is not intended functionality.

> At one point there was an option in Tweak app > Extensions > Pop cosmic > gear that could fix it. I was able to do something with the Super key in there (I don't remember what) but that option is no longer available.

That setting was added [here](https://github.com/pop-os/cosmic/pull/183) and later reverted because it caused an issue similar to the one you're describing. However, it's strange that you're still seeing the issue after updating to the reverted version. There's an open PR [here](https://github.com/pop-os/cosmic/pull/197) to re-introduce the option, hopefully without the issue this time.

How often does this occur on your machine? Does anything in particular (such as locking and unlocking the screen) trigger the issue? (Do you think you'd be able to tell if the version in pop-os/pop#197 no longer has the issue?)

**Comment by ghost** [comment]
> However, it's strange that you're still seeing the issue after updating to the reverted version. 

Is it possible that there's a settings file lingering somewhere that's still triggering the problem?

> How often does this occur on your machine?

At least once per session. I'm usually too lazy to fix it by logging out.

> Does anything in particular (such as locking and unlocking the screen) trigger the issue?

I work with Godot and Blender, and at first I thought there was a correlation to opening those. However, I think it happens most often when opening any application really. That said, many of my installed applications are Flatpak, so maybe a correlation there?

> (Do you think you'd be able to tell if the version in [pop-os/pop#197](https://github.com/pop-os/pop/issues/197) no longer has the issue?)

I couldn't say. This is a new install and I've never worked with 18.04.

**Comment by ghost** [comment]
**A quick note**: almost immediately after I submitted this bug, several updates were pushed to my machine. I installed them and have yet to experience the issue. I'm leaving this open for now, but I'll update as soon as necessary.

**Comment by jacobgkau** [comment]
> Is it possible that there's a settings file lingering somewhere that's still triggering the problem?

There's no settings file. The setting in question was a gsetting, but the version that doesn't have the setting in its GUI also shouldn't be reading the setting behind the scenes.

> I couldn't say. This is a new install and I've never worked with 18.04.

Sorry, https://github.com/pop-os/pop/issues/197 is completely unrelated to this. I was trying to link to https://github.com/pop-os/cosmic/pull/197. (I had to transfer this issue to the correct repository, and I think that messed my link up.)

> **A quick note**: almost immediately after I submitted this bug, several updates were pushed to my machine. I installed them and have yet to experience the issue. I'm leaving this open for now, but I'll update as soon as necessary.

Please do let us know if it starts happening again. If it doesn't, then I would assume this was a case of an update not making its way to your machine. Either way, we do want to move forward with testing https://github.com/pop-os/cosmic/pull/197 to re-introduce the option, but making sure the issue doesn't happen anymore before merging.

If you'd like to test that version out, you can install it using these commands:

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add testing-cosmic-pr197
sudo apt update
sudo apt full-ugprade
```

Then to revert to the normal version later, you can run:

```
./pop/scripts/apt remove testing-cosmic-pr197
sudo apt update
sudo apt full-upgrade
```

**Comment by ghost** [comment]
It has now been 10 days of solid use, and the issue has not come up again. Seems like the updates fixed the issue.

My machine has received a stern talking to, and has promised to not hold back updates again.
