### ISSUE TITLE
Reimplement moving the workspace picker and default to left

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell-extension-pop-cosmic#206]

**Comment by ids1024** [comment]
Probably should add an update on this here. `gnome-shell-extension-vertical-overview` now has a setting for this, defaulting to left. This still needs to properly be connected to the setting in desktop-widget in some way. (We probably want upgrades to persist the setting if the user set it to the right, so it needs to either use the gsettings key from Cosmic, or somehow migrate the setting on upgrade.)

**Comment by ids1024** [comment]
> so it needs to either use the gsettings key from Cosmic...

Implemented this way in https://github.com/pop-os/gnome-shell-extension-vertical-overview/commit/7beb35958aec84d1360573a86e77728bafdfebd2.

So this functionality should be working as desired. Closing.
