### ISSUE TITLE
Make Applications Library its own window 

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/gnome-shell-extension-pop-cosmic#207]
New designs for making the Application grid (now renamed Applications Library) its own floating window: https://www.figma.com/file/SpjW7ksxjSfXxHmKROdwb3/Application-Library?node-id=268%3A1180
The styling overall would match the Launcher better and the behavior in some respects should be similar:
- displays on the focused monitor like the Launcher
- people should be able to click away from it.

Unlike the Launcher we might want to have a smoother fade in animation for this window. See clickable mockups for general direction: https://www.figma.com/proto/SpjW7ksxjSfXxHmKROdwb3/Application-Library?node-id=268%3A1288&scaling=scale-down&page-id=268%3A1180&starting-point-node-id=268%3A1288&show-proto-sidebar=1

Other things to note:
- Users should be able to drag and drop apps to COSMIC Dock.
- Pages act like a carousel and one can go in a circle between them.
- Scrolling moves between the pages. 
- Clicking on arrows moves between the pages but dots are not clickable, they serve to indicate the number of pages and to orient people as to what page they are on. 
- Folders should be available at release (mockups for how they could be created, named and destroyed are coming).
- Application Icons are sorted alphabetically by default but could be arranged manually. There should be a dropdown in Desktops > General in Settings for that. Here is the mokcup (note the use of Applications Library throughout this panel):
![settings-desktop-general](https://user-images.githubusercontent.com/57502897/134258159-60614b4a-d96d-4d68-afa8-b7c91a0446fe.png)
- When display is set to Vertical, the app grid re-arranges to match the display (using mockups as example that would mean switching from 7x3 to 5x4 grid). 

I can provide more detailed notes for spacing, padding and sizing if necessary in case those are difficult to gauge in Figma, just let me know.

**Comment by ids1024** [comment]
The search feature in Gnome Shell displays search results from multiple "search providers", including applications.

I suppose we want to remove that functionality, and have the search here just filter the applications list?

**Comment by maria-komarova** [comment]
We want the search to filter the application list but also Pop!_Shop. "available to Install" section in the search results should expose those.

**Comment by jackpot51** [comment]
Continued in https://github.com/pop-os/cosmic/issues/228
