### ISSUE TITLE
Please don't :(

### ISSUE THREAD

**Issue by roracle** [pop-os/gnome-shell-extension-pop-cosmic#21]
Yes, I know these changes are due to the statistics about users installing docks. But that's perfectly normal activity.

I use dash to panel, and it's just fine. This is just extra, and the changes I've seen y'all make (for example, meta opening a text based launcher) is going to turn off a number of people I know who have been using your system.

Please, as a dock user, I'm begging you guys to end this project and start contributing to Gnome 40 instead.

Don't make 20.04 the "last good Pop OS version" because so many distros do exactly what you're doing. They get popular because of interest in a custom interface, then die almost instantly when the average user realizes how unnatural it is to use.

Even Gnome 3 gets it wrong: meta should open applications, and meta+a should show activities, especially since there's a literal "activities" button by default. (Which can be improved on with hot corner activation of activities). 

The redundancy of access is throwing away common sense on the whole.

Take it from an artist: there's no shame in scrapping a project when it's clearly a vanity project.

Here's your sign.

**Comment by philibertc** [comment]
Hello @roracle,
Pop_COSMIC is a gnome extension, you should be able to simply deactivate it and go back to a regular GNOME.
However, have you tested COSMIC?

**Comment by roracle** [comment]
> Hello @roracle,
> Pop_COSMIC is a gnome extension, you should be able to simply deactivate it and go back to a regular GNOME.
> However, have you tested COSMIC?

Not yet I haven't, but I've seen the videos and I don't like what I've seen. The people doing the videos don't really seem to have an opinion outside of "but it's not done yet, so let's see where this goes".

But I've noticed that I've never seen two desktops that look the same unless it's a fresh install.

**Comment by WatchMkr** [comment]
The design and engineering work being done here is the result of over a year of user research with customers and users. The UX, design, and engineering work is not complete and is ongoing.
