### ISSUE TITLE
[Feature Request]: Ability to get back applicaiton button with app name

### ISSUE THREAD

**Issue by Swat-SomeBug** [pop-os/gnome-shell-extension-pop-cosmic#213]
I switched to using the COSMIC desktop on Pop!_OS and things are working great for me.
However, I'm currently missing the Gnome feature which lists the active application on the top panel.
Upon clicking the application name, an open windows list is present which is very helpful for me when I have several PDFs/Images open. I could quickly jump to the file I needed.
Could this feature be added back in COSMIC?

**Comment by senntore** [comment]
If this is what you mean
![Screenshot from 2021-10-101](https://user-images.githubusercontent.com/58325574/136683019-eea5105e-228f-4eda-9986-d1fc9e83416f.png)

You can easily do this via launcher by pressing Super key & selecting your window of your choice. See here
![Screenshot from 2021-10-10](https://user-images.githubusercontent.com/58325574/136683068-3f3d3d0a-e01c-452f-86f3-a874bc465abf.png)

Also if your system is up-to-date, then you can enable windows preview for dock in dock settings(for icon click action) & quickly navigate between windows from dock itself.
![Screenshot-2021-10-10,10-41-33](https://user-images.githubusercontent.com/58325574/136683213-7088d187-8a78-4b2c-8a7a-80be92e6f48d.png)

If you're satisfied with these options, then consider closing this issue/feature request.

**Comment by Swat-SomeBug** [comment]
Yes. Having the ability to get back the `Files` menu as an option in the COSMIC settings is what I mean.
`Show Applications` and `Show Workspaces` options are already there in the settings for both the top panel and the dock and are enabled by default. The request is to have an option in the COSMIC settings to turn on the app menu in the panel as well.

I currently use both `Workspaces` buttons, the one in the dock as well as the one on the top panel, depending on where the cursor is at any time. It would be great to have the ability to do the same with the app itself. The app menu also gives options to create a new window and quit. So having the ability to do all these actions from the top panel and the dock would be appreciated.

**Comment by senntore** [comment]
> The app menu also gives options to create a new window and quit

You have this option in dock as well. Right clicking on an app icon gives you options for new windows, quit, etc. While left clicking will show you window previews(if multiple windows are open), if you've enabled windows previews from dock settings.

**Comment by Swat-SomeBug** [comment]
> You have this option in dock as well. Right clicking on an app icon gives you options for new windows, quit, etc.

Yes. I use it quite a lot. As I said, the usage is based on where the mouse cursor is at any given time. If the cursor is closer to the dock using the dock makes sense.
It’s the same with workspaces or the app grid. Both options are available from the dock as well as the top panel and one may use either (or disable either/both depending on personal workflows).

**Comment by ThePhxRises** [comment]
I would also like to add my voice to this, I would like an option to restore this functionality too so that the active window is instantly identifiable without the active hints enabled.
