### ISSUE TITLE
[Feature] Ability to easily open program as superuser

### ISSUE THREAD

**Issue by SekoiaTree** [pop-os/gnome-shell-extension-pop-cosmic#217]
If I want to change some configuration file, it's often easiest to open the file manager as superuser (since all the config files are in admin folders). However, as far as I know, the only way to do this is through the commandline, which is unwieldy and annoying (especially since the name doesn't always match up to the command... nautilus, for example). It would be great if we could open any program with sudo with a right click, and/or a keybinding.
I might try to do this myself, if I figure it out.

**Comment by ids1024** [comment]
Running GUI programs as root is generally considered a bad practice. And while Pop currently uses Xorg, it wouldn't work under Wayland.

The Arch Wiki has some more information about this: https://wiki.archlinux.org/title/Running_GUI_applications_as_root

**Comment by SekoiaTree** [comment]
I see. The link you sent does have a way for nautilus, so that covers most of my usecases (although I'd enjoy a GUI button for it), so I'll close this for now, thanks!
