### ISSUE TITLE
How to translate the application menu?

### ISSUE THREAD

**Issue by philibertc** [pop-os/gnome-shell-extension-pop-cosmic#22]
Hello,
How to translate the application menu especially the search field?
![image](https://user-images.githubusercontent.com/57588282/115255446-8fea5a00-a12e-11eb-84d1-d6df4315d201.png)
I did not find anything in the extension files corresponding to this part of COSMIC.

**Comment by jackpot51** [comment]
That comes from github.com/pop-os/shell

**Comment by philibertc** [comment]
Okay, thanks.
