### ISSUE TITLE
Please change to Horizontal workspaces switcher.

### ISSUE THREAD

**Issue by spirulin** [pop-os/gnome-shell-extension-pop-cosmic#236]
I know you have your own vision, I was too used to vertical from Ubuntu and then Pop but after I tried Fedora I got used to the new switcher in coupe minutes.

It feels more natural for your screen to change to the sides instead of weirdly going up or down.

Or please add an option the user to choose how they would like to have it.

Thank you for your work.

**Comment by IlChitarrista** [comment]
Hi, I've questioned myself about this and I've noticed that, in the Beta for Pop!_OS 21.10, you can disable the Extension that makes the Workspaces vertical for, in Gnome 40, they are horizontal by default; This is not an actual solution for it breaks the beautiful color scheme of Pop!_OS and the workspace switching shortcut, at least in a WM, does not work.

Personally I think that choice is the most important quality an OS should have but, not only this is relatively low priority considering it has always been this way on Gnome, it is also something that, for a fully polished distro, comes in second after the actual UX choices of the developers which are of the outmost importance, especially for new users oriented OSes.

Also, quick little thing, this question has already been asked (https://github.com/pop-os/cosmic/issues/30) so I would suggest you to close this issue and comment under the original one to make it more evident.

**Comment by leviport** [comment]
Thank you for the feedback! This feature was already requested here: https://github.com/pop-os/cosmic/issues/30. This is still a feature we'd like to implement, but there are quite a few higher priority items at the moment.
