### ISSUE TITLE
Duplicate buttons for workspaces and applications: useful or redundant?

### ISSUE THREAD

**Issue by janopae** [pop-os/gnome-shell-extension-pop-cosmic#25]
Hi! I know that Cosmic Shell has been developed based on research and user feedback. However, one thing that appears kind of odd to me about the design concept, is that both buttons, the one for the workspace overview and the one for the application launcher, exist two times on the desktop: One time in the top bar and one time in the bottom dock.

Is this based on the observation that some users expect these buttons to be in the dock and some expect them to be in the top bar? I haven't done any particular studies on this particular decision, but redundancy in user interfaces is known as a likely source of confusion and gives the impression of an unclear concept and therefore is often considered an anti-pattern. Having all functions everywhere might increase the number of users finding them on the first try, but on the long run, it will raise questions whether the buttons actually do the exact same thing and clutter up the interface. Instead, it's generally recommended to go for a "single source of truth" approach.

That's why I'd Instead suggest having the application launcher only in the dock and the workspace overview only in the top bar by default. This suggestion is based on the following arguments:

## Familiarity

One thing that massively helps understanding a new user interface is the use of patterns that users might know and be familiar with. Some patterns are so widely adopted that they became a sort-of standard - think about scroll bars for example.

Many popular desktop environments have the application launcher accessible as a button in the dock and an overview of the opened windows in the top-left corner. This is true at least for MacOS, Ubuntu and KDE Plasma.

The application launcher being in the same bar/dock as the favourite and opened applications is even more common: This is the case for Windows, MacOS, Gnome (Ubuntu), Gnome (Vanilla), KDE Plasma, Unity, Android and many more, and therefore could be considered a sort-of-standard in my opinion.

No desktop environment I know besides Unity and Gnome 2, which both can be considered out of use, has the application launcher at the top-left corner, or even in the top bar.

## Semantic context

At least for the application launcher, it also makes sense from a semantic standpoint to have it in the same place where favourite and opened applications are: That means that when the user wants to start an application, they know they're going to find it in the dock. The application launcher kind of gets the function of a "read more" button of a truncated application list, if that is understandable. There is no such argument for having the application launcher in the top bar.

The top bar however is the place from which tiling is controlled in PopOS. That kind of makes it the right place for a window management feature like the workspace overview, from a semantic standpoint.

I hope this issue somehow makes sense and does not repeat a discussion you already had internally when working out the design concept. The rest of the UI concept looks very sane and well-thought to me, I really look forward to see this being ready to use!

**Comment by PTrottier** [comment]
Thoughts from another user:

> That's why I'd Instead suggest having the application launcher only in the dock and the workspace overview only in the top bar.

I understand the perspective being presented here and generally agree with what is being said. However, the Settings > Desktop > Desktop does have options to remove the buttons in the title bar and Settings > Desktop > Dock will soon have the option to remove them from the toolbar. Therefore, I prefer the current approach because it helps for discovery but can be customized in the future for minimalism and efficiency. This could also flow well with a new user's understanding of the system, as they become more proficient, they discover these features in the Settings. I love the flexibility offered by COSMIC :)

**Comment by WatchMkr** [comment]
We're supporting the option to use a dock or not have a dock at all. The current beta ISO has Applications and Workspaces in both places; however, a feature being designed for first time user setup will provide the option of starting with or without the dock. 

With a dock will exclude Applications and Workspaces in the top bar and likely move the clock to the left position by default (which can be changed in Settings).

Without a dock will set Workspaces and Application at the top left of the bar and the clock in the middle.
