### ISSUE TITLE
Icons oversized and hidden in applications grid

### ISSUE THREAD

**Issue by Swat-SomeBug** [pop-os/gnome-shell-extension-pop-cosmic#254]
I just updated to the latest released Pop-COSMIC version on Pop!_OS 21.10 (+ logout and re-login) and I find apps are not displayed properly in the app grid as shown in the screenshot.

![PopOS-Cosmic-app-grid issue](https://user-images.githubusercontent.com/83545272/144707218-79a1b0e2-2e6c-41e8-b22c-fd953baa6108.png)

Several apps cannot be seen because of the scaling issue. Partially seen apps can be interacted with and launched.

**Comment by leviport** [comment]
This is the old application library design. 21.10 has the new application library update available. I recommend a `sudo apt update && sudo apt full-upgrade` followed by a reboot.

**Comment by Swat-SomeBug** [comment]
Reboot fixed it... thanks 👍🏼
