### ISSUE TITLE
Option to save windows session apps and position

### ISSUE THREAD

**Issue by lgonzalezsa** [pop-os/gnome-shell-extension-pop-cosmic#255]
Running Pop!_OS 21.04 with GNOME Version 3.38.5 and wondering if there is an option to save current windows session layout, all apps opened and the position in the different workspaces?
This will save a lot of time when need to reboot for kernel upgrade or switch to do different activities, then just load again the required layout with the apps and the position.

**Comment by jacobgkau** [comment]
This sounds like it may be a duplicate of https://github.com/pop-os/shell/issues/735.

**Comment by lgonzalezsa** [comment]
Agree, closing in favor te of [pop-os/shell#735](https://github.com/pop-os/shell/issues/735).
