### ISSUE TITLE
Re-base to GNOME 40?

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#26]
Will COSMIC Desktop ever be re-based to Gnome 40?

**Comment by mmstick** [comment]
I'm sure it can supported with a patch, if anyone's willing to do the work. We don't have to support GNOME 40 until Ubuntu does.

**Comment by carlwgeorge** [comment]
Based on recent news it sounds like Gnome 40 is coming to Ubuntu 21.10.  Can this issue be left open for those that want to subscribe to be notified about cosmic's progress towards Gnome 40 compatibility?
