### ISSUE TITLE
Applications library: better support for smaller resolutions

### ISSUE THREAD

**Issue by khulay** [pop-os/gnome-shell-extension-pop-cosmic#264]
I tried installing Pop OS 21.10 on my laptop, but when I open the Applications Menu the size is large and different from Release Image, how do I fix it? My resolution is 1366x768

On My PC

![](https://user-images.githubusercontent.com/90043252/146138279-ebee6ed9-1c4a-4c02-b089-8c84601e4f81.png)

Release Image

![](https://user-images.githubusercontent.com/90043252/146138590-7d4a3165-dff6-4fab-8b48-df634425ec93.png)

**Comment by leviport** [comment]
Thank you for the report! Improved support for <1080p resolutions is actively being worked on.

**Comment by rickm00** [comment]
I am experiencing the same problem by following along...

**Comment by rickm00** [comment]
I am experiencing the same problem by following along

**Comment by rckmachado** [comment]
I'm sorry but this problem return in the last update :(

![Screenshot from 2022-02-21 08-42-56](https://user-images.githubusercontent.com/32842682/154953738-e8c23128-b225-46fe-a6f4-6d94bca3eb4d.png)

**Comment by jacobgkau** [comment]
We will continue the conversation in https://github.com/pop-os/cosmic/issues/314 since you opened another issue anyway.
