### ISSUE TITLE
If COSMIC is disabled... when GNOME is reloaded it automatically brings you to the activities view

### ISSUE THREAD

**Issue by rojizo** [pop-os/gnome-shell-extension-pop-cosmic#265]
It is a pretty anoying problem. At first I thougt was a problem with the configuration I bring to Pop from previous version but not! It appears if I disble COSMIC. 

When you log in, it goes to activities view instead to the desktop. So you are stuck with either COSMIC or with the glitch

On PopOS 21.10.

**Comment by ids1024** [comment]
> or with the glitch

Actually it's not a glitch. This is intentional behavior in stock Gnome 40+, which Cosmic disables.

Without Cosmic, this extension should do the same: https://extensions.gnome.org/extension/4099/no-overview/

**Comment by rojizo** [comment]
I realized my error later when I checked Fedora... Closing!

And thx for the extension...
