### ISSUE TITLE
Unable to add apps to favorites from App Library

### ISSUE THREAD

**Issue by darkmethatx** [pop-os/gnome-shell-extension-pop-cosmic#267]
Possible bug with adding Screenshot app to favorites list.

**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

App - GNOME Screenshot v. 3.36.0

**Issue/Bug Description:**

In Pop OS>Activities>All apps>Utilities>right-click on Screenshot app>select Add to favorites>it opens the Pop!_shop app and takes me the GNOME Screenshot app download page.

**Steps to reproduce (if you know):**

Pop OS>Activities>All apps>Utilities>right-click on Screenshot app>select Add to favorites>it opens the Pop!_shop app and takes me the GNOME Screenshot app download page. This is not expected as I'm simply trying to add the app to my favorites list.  

**Expected behavior:**
Users should be able to add Screenshot app to favorites list instead of taking them to the Pop!_Shop application page.  

**Other Notes:**
Other apps I'm able to add/remove from favorites list.  This app, I simply cannot. I appreciate any assistance.

**Comment by marklabrecque** [comment]
ok thanks @jacobgkau - Thanks for pointing this out. They did originally look related, but I see now how they could be coincidentally similar.

Now that I am trying to record steps to reproduce it, I am not seeing it, but if it shows up again, I will create a fresh ticket.

Cheers!

**Comment by jacobgkau** [comment]
> Now that I am trying to record steps to reproduce it, I am not seeing it, but if it shows up again, I will create a fresh ticket.

This is not a ticket, it is a bug report on a development platform. If it happens again, leave a comment here and we will re-open.
