### ISSUE TITLE
Pop_OS cosmic dock not minimize window 

### ISSUE THREAD

**Issue by ynoalberto** [pop-os/gnome-shell-extension-pop-cosmic#272]
Dock os Pop_OS Cosmic does not minimie windows when I make click with the mouse in the icon program in the dock in gnome 40

**Comment by leviport** [comment]
Please check Settings > Desktop > Dock > Dock Options > Icon Click Action

If I'm understanding correctly, I believe setting it to "Launch or Minimize Windows" will make it do what you're looking for.

**Comment by ynoalberto** [comment]
Thanks you. I could fix it. Sorry for the inconvenence

**Comment by leviport** [comment]
No worries, glad you were able to fix it
