### ISSUE TITLE
system tray icons bug blank icons they create themselves 

### ISSUE THREAD

**Issue by tridoxx** [pop-os/gnome-shell-extension-pop-cosmic#274]
hi, bug is system tray icons, create blank invisible spaces, it hapen many times, idk what create the problem, but when i run more of 4 apps that have system tray icons that happen, and i click and nothing happen in this picture i have 2 blank tray icons. 
this happen in the update of 21.10 in 21.04 i was install a extensión from trayicons, keep on the bar. 
![asd](https://user-images.githubusercontent.com/22879539/146962536-92a88b06-5bc0-4ff2-9e33-07a8c90b7496.png)

**Comment by cheetahdotcat** [comment]
![image](https://user-images.githubusercontent.com/99863633/163557385-8d3bbaf6-cddf-4145-ae2d-32681ada3f28.png)
I have the exact same problem.

**Comment by tridoxx** [comment]
> ![image](https://user-images.githubusercontent.com/99863633/163557385-8d3bbaf6-cddf-4145-ae2d-32681ada3f28.png) I have the exact same problem.
@cheetahdotcat hey, hi, in the last update, look that is fixed, for me work normaly now

**Comment by cheetahdotcat** [comment]
yup, its fixed

**Comment by tridoxx** [comment]
in the latest versions they are not failing to date we are in gnome42 with pop_os 22.04.
