### ISSUE TITLE
Desktop Gets Stuck in Workspaces View

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell-extension-pop-cosmic#29]
Workspace previews/picker are not present when the desktop gets stuck on the Workspaces view.

**Comment by jackpot51** [comment]
This looks to be introduced by super key action changes in COSMIC and Shell

**Comment by DuttaAB-dev** [comment]
This issue persists even if the super key is reassigned to the workspaces view.

**Comment by bflanagin** [comment]
This may be relevant to our issue. 

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2327

**Comment by jacobgkau** [comment]
Instructions to recreate posted here: https://github.com/pop-os/beta/issues/144#issuecomment-854145459

**Comment by mmstick** [comment]
Fixed by GNOME Shell update
