### ISSUE TITLE
Application Library doen't fit in screen with hidpi scaling, i.e. 4k with 200%.

### ISSUE THREAD

**Issue by kornerita** [pop-os/gnome-shell-extension-pop-cosmic#290]
Hi,

Today I've upgraded my pop os system 21.10 to last changes, after the reboot the App Library doen't fit the screen and it hides the folders on the bottom.

Related post: [https://www.reddit.com/r/pop_os/comments/s0vftk/show_applications_is_seemingly_bugged_on_my_system/](url)

Screen res 3840x2160 no scaling:
![Captura de pantalla de 2022-01-10 20-55-50](https://user-images.githubusercontent.com/26329207/148870629-6c6482d4-6898-474d-a817-ae0f15ef56c3.png)

Screen res 3840x2160 with 200% scaling:
![Captura de pantalla de 2022-01-10 20-55-31](https://user-images.githubusercontent.com/26329207/148870705-c2077943-d496-4521-aa41-c59e93d50882.png)

Last entry on `/var/log/apt/history.log`

`Start-Date: 2022-01-10  18:35:14
Commandline: apt upgrade
Requested-By: ***** (1000)
Install: linux-image-5.15.11-76051511-generic:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-tools-5.15.11-76051511:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), system76-scheduler:amd64 (0.1.0~1641485736~21.10~8066426, automatic), linux-headers-5.15.11-76051511-generic:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-cloud-tools-5.15.11-76051511-generic:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-modules-5.15.11-76051511-generic:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-tools-5.15.11-76051511-generic:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-headers-5.15.11-76051511:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic), linux-cloud-tools-5.15.11-76051511:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, automatic)
Upgrade: linux-system76:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), linux-tools-common:amd64 (5.15.8-76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21), linux-headers-generic:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), pop-launcher:amd64 (1.1.0~1638290853~21.10~98e3866, 1.1.0~1640207101~21.10~3b4136e), popsicle:amd64 (1.3.0~1637606351~21.10~8958ab3, 1.3.0~1640021224~21.10~b02ebf5), pop-desktop:amd64 (1.6.0~1635432906~21.10~241a4cf, 1.6.0~1641605623~21.10~53155a1), pop-gtk-theme:amd64 (5.4.5~1634918910~21.10~23d7ac8, 5.4.5~1641605661~21.10~164d6ef), gnome-shell-extension-cosmic-workspaces:amd64 (0.1.0~1635961632~21.10~d0b2d18, 0.1.0~1641605668~21.10~fefa2b3), libpop-desktop-widget:amd64 (0.1.0~1637024235~21.10~f7a34e7, 0.1.0~1641227351~21.10~9ca8b68), pop-default-settings:amd64 (5.1.0~1638298037~21.10~77e14a2, 5.1.0~1640204937~21.10~3f0be51), system76-power:amd64 (1.1.20~1637635456~21.10~b5ed171, 1.1.20~1640721511~21.10~5166682), pop-cosmic:amd64 (0.1.0~1639487583~21.10~9bc4666, 0.1.0~1640211540~21.10~73b0c61), linux-generic:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), pop-gnome-shell-theme:amd64 (5.4.5~1634918910~21.10~23d7ac8, 5.4.5~1641605661~21.10~164d6ef), gnome-shell-extension-cosmic-dock:amd64 (70~ubuntu1pop0~1639487648~21.10~3c3f377, 70~ubuntu1pop0~1641401554~21.10~4c62ba4), gnome-shell-extension-desktop-icons-ng:amd64 (20-1pop0~1637682135~21.10~2a407ca, 33-1pop0~1640036051~21.10~84fc73c), linux-cloud-tools-common:amd64 (5.15.8-76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21), popsicle-gtk:amd64 (1.3.0~1637606351~21.10~8958ab3, 1.3.0~1640021224~21.10~b02ebf5), linux-image-generic:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), pop-shell:amd64 (1.1.0~1639174177~21.10~de901ae, 1.1.0~1641595320~21.10~c3d93f8), linux-tools-generic:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), pop-sound-theme:amd64 (5.4.5~1634918910~21.10~23d7ac8, 5.4.5~1641605661~21.10~164d6ef), linux-cloud-tools-generic:amd64 (5.15.8.76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21), system76-acpi-dkms:amd64 (1.0.2~1635519829~21.10~b49caa5, 1.0.2~1640122755~21.10~04145b8), linux-libc-dev:amd64 (5.15.8-76051508.202112141040~1639505278~21.10~0ede46a, 5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21)
End-Date: 2022-01-10  18:36:37`

Thank you for your time,
Federico.

**Comment by park** [comment]
Some here. Will be waiting for a fix.

**Comment by ghost** [comment]
I can also observe a similar behaviour, but with a 1920x1080 screen resolution when fractional scaling (125%) is enable on my second monitor (same resolution).

**Comment by pbui** [comment]
@kornerita @park @guillaumedum Could you try the fix in #277?

I have updated it to also factor in the resolution of the monitor.

**Comment by kornerita** [comment]
> @kornerita @park @guillaumedum Could you try the fix in #277?
> 
> I have updated it to also factor in the resolution of the monitor.

Hi,

I've tried the fix, still not the expected behaviour, now in 100% scaling is not showing folders, fits all screen in every scaling:

3840x2160 200% scaling:
![Captura de pantalla de 2022-01-11 06-08-46](https://user-images.githubusercontent.com/26329207/148915304-9dbe911d-1144-40a7-99c5-38f4a750d43c.png)

3840x2160 100% scaling:
![Captura de pantalla de 2022-01-11 06-11-33](https://user-images.githubusercontent.com/26329207/148915392-a7feb6e8-cd0c-4871-994b-cb2e845ea041.png)

**Comment by pbui** [comment]
@kornerita Based on the shape of the your search box, that looks like the default GNOME overview and not the Pop Cosmic application library... Can you verify that the Pop Cosmic extension is active?

**Comment by kornerita** [comment]
Sorry I'm as noob as it gets, I did something wrong with the fix installation....

Now  i've cloned the pop-os/cosmic repo and replace the application.js file with the patched one...

now it kinda works but it's really too big, I mean, it's a waste of screen...  specially without scaling, maybe adding a way to select the amount of icons o icon size?

3840x2160 100%
![Captura de pantalla de 2022-01-11 09-29-01](https://user-images.githubusercontent.com/26329207/148942736-7a61ceac-cd5e-4d20-b249-11e1285a726b.png)

3849x2160 200%
![Captura de pantalla de 2022-01-11 09-29-28](https://user-images.githubusercontent.com/26329207/148942847-35c3e85a-5be8-4b0b-8d20-d97df5b07e08.png)

PS: If i'm applying the fix wrong, it woild be nice if you could point me to the correct method, tyvm!

Edit: maybe find a way to get icon sizes of the main screen consistent with the folders below

**Comment by pbui** [comment]
OK.  At least that fixes the application window size.

Basically the issue is that I am always scaling the icons to match the density at 1920x1080.  This is useful for smaller resolutions.

For resolutions larger than 1920x1080 (like yours), I should allow for even more density (ie. more icons).

I'll take a stab at that in a little bit.  Thanks for checking it out.

PS. As to how to apply the fix, you can checkout what I wrote here: https://www.reddit.com/r/pop_os/comments/s0vftk/comment/hs75na6/?utm_source=share&utm_medium=web2x&context=3

**Comment by ghost** [comment]
> @kornerita @park @guillaumedum Could you try the fix in #277?
> 
> I have updated it to also factor in the resolution of the monitor.

Thank you for the quick follow-up on this issue. 

I have tried your fix and it seems to have resolved the problem on my setup (1 screen at 1920x1080 w/o scaling and 1 screen at 1920x1080 with 125% scaling).

**Comment by pbui** [comment]
@kornerita I just pushed an update that caps the iconScaling to 1, which should allow for increased icon density at higher resolutions.  Could you download the latest version of that fix and see if it works better at 4k?

**Comment by pbui** [comment]
@guillaumedum Thanks for letting me know.

**Comment by kornerita** [comment]
@pbui Thank you, ok so this fixes the issue as intended.

I see no difference with the iconScaling to 1, I've tested it both.

As for my personal take on this, it would be nice just to have an option like the one that lets you choose the px size of the dock in Configuration > Desktop > Dock, so users can choose their amount / relative size of icons that they want to see in cosmic.

**Comment by ronellsalunke** [comment]
> I can also observe a similar behaviour, but with a 1920x1080 screen resolution when fractional scaling (125%) is enable on my second monitor (same resolution).

Can confirm the same when I'm set to 125% scaling on my 15.6in 1080p screen. Attached a screenshot for reference.
![Screenshot from 2022-01-11 23-32-43](https://user-images.githubusercontent.com/37792939/148997103-4323830f-fc91-498e-b88e-7799c673c2a1.png)

**Comment by pbui** [comment]
@ronell1292k Can you try the fix in #277 ?

**Comment by MichelN86** [comment]
Got the same issue on 2 other machines since the last updates from yesterday

https://i.imgur.com/MZWucXT.png

**Comment by oguzkarayemis** [comment]
Same here with 3200x1800 and %200 scaling rate.
![Ekran görüntüsü 2022-01-12 10-46-43](https://user-images.githubusercontent.com/80787950/149085860-38fa8d32-2994-417e-a14e-fbf3eabea1ac.png)
![Ekran görüntüsü 2022-01-12 10-47-29](https://user-images.githubusercontent.com/80787950/149085866-70970dd1-2855-4f84-ab1f-905978ff6673.png)

And I can confirm this solution worked for me:

> OK. At least that fixes the application window size.
> 
> Basically the issue is that I am always scaling the icons to match the density at 1920x1080. This is useful for smaller resolutions.
> 
> For resolutions larger than 1920x1080 (like yours), I should allow for even more density (ie. more icons).
> 
> I'll take a stab at that in a little bit. Thanks for checking it out.
> 
> PS. As to how to apply the fix, you can checkout what I wrote here: https://www.reddit.com/r/pop_os/comments/s0vftk/comment/hs75na6/?utm_source=share&utm_medium=web2x&context=3

**Comment by ronellsalunke** [comment]
> @ronell1292k Can you try the fix in #277 ?

fix in #277 works as intended. Thanks for the prompt reply!
![Screenshot from 2022-01-12 14-02-00](https://user-images.githubusercontent.com/37792939/149091788-a1f032e5-d6ff-4d48-b3bc-de6b1a0684e7.png)

**Comment by MichelN86** [comment]
This fixed it for me https://www.reddit.com/r/pop_os/comments/s0vftk/comment/hs75na6/?utm_source=share&utm_medium=web2x&context=3

**Comment by Whats-the-time** [comment]
Thanks for the fix regarding the floating window.  Can confirm it works.  Can also confirm icon size scaling still needs work.

3840x2160 @ 200%
![Screenshot](https://user-images.githubusercontent.com/97655442/149376405-d1cc3e24-a884-4dcc-a654-787e063858d1.png)

3840x2160 @ 100%
![Screenshot2](https://user-images.githubusercontent.com/97655442/149377425-674029c0-48fe-4458-af40-5148dfd99080.png)
