### ISSUE TITLE
Detail of the icon selection in the Dock

### ISSUE THREAD

**Issue by rckmachado** [pop-os/gnome-shell-extension-pop-cosmic#291]
When some applications are open and we hover the mouse between the active icons, the check mark runs out of separation space, making the interface look very strange.

![Captura de tela de 2022-01-11 09-01-15](https://user-images.githubusercontent.com/32842682/148999445-0cbf085f-c6dc-47a2-9e1d-a33cb27322a0.png)

**Comment by leviport** [comment]
That styling looks correct to me. The visual indicators are intended to touch each other.
