### ISSUE TITLE
[Feature Request] Add multi monitor Top Bar support

### ISSUE THREAD

**Issue by OverlordMarkus** [pop-os/gnome-shell-extension-pop-cosmic#292]
Similarly to the option to have the dock appear on all monitors, add the option to have the top bar appear on all monitors.

Usecases:

- Full Screen applications / games
- Setups with more than two monitors
- Laptop setups with additional monitors
- Workspace heavy-users with two or more monitors

**Comment by JoshuaLeivers** [comment]
Are there currently any compatible GNOME extensions that could do this outside of changes to Pop?

**Comment by theaupoulat** [comment]
There is [this GNOME extension](https://extensions.gnome.org/extension/921/multi-monitors-add-on/) but seems incompatible with the latest version of PopOS.

**Comment by AlexAtkinson** [comment]
Multi-monitor support is a hard requirement. Please add this.
No, the extension is not a suitable solution.

**Comment by aniwid** [comment]
+1 for this! Also make it customizable. Like having just the bar with the time on it on all monitors, I don't necessarily want Workspaces/Applications or power/sound etc.

**Comment by leviport** [comment]
This is an implemented feature in COSMIC DE. The panel (aka top bar) is also highly configurable.

Note: this repository is for the old set of Gnome extensions that we used to refer to as "COSMIC". For COSMIC DE, see https://github.com/pop-os/cosmic-epoch and the various submodules within.

**Comment by MendyBerger** [comment]
@leviport mind pointing out where this can be configured?

**Comment by leviport** [comment]
Settings > Desktop > Desktop and Panel

And again, this is for COSMIC DE only.

**Comment by aniwid** [comment]
> Settings > Desktop > Desktop and Panel
> 
> And again, this is for COSMIC DE only.

Ah right, I think I'll wait until COSMIC becomes a bit more finished than pre-alpha before installing it just for the time to be on all my monitors :)
