### ISSUE TITLE
App Wall > Limit search results to installed and available applications

### ISSUE THREAD

**Issue by jackpot51** [pop-os/gnome-shell-extension-pop-cosmic#3]

**Comment by jackpot51** [comment]
Implemented in https://github.com/pop-os/session/commit/a785d41144a1226f3a2c9990d635f2c621eb7922

**Comment by jroyvde** [comment]
Power and session options still seem to show up in the App Wall, even with all Search Providers besides Pop!_Shop disabled.

![COSMIC App Wall](https://user-images.githubusercontent.com/54386705/120053400-3b12fb00-c06d-11eb-9961-4d9e5ac10075.png)
