### ISSUE TITLE
[bug] Keyboard shortcut `Super`+`Alt`+`Up` twice summons a broken version of the old Applications picker

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-shell-extension-pop-cosmic#300]
Pressing this key combo once takes me to the Workspaces view. Pressing it again keeps the workspace picker visible, but displays application icons. I'm not sure what the key combo is supposed to do, but we probably don't want it doing this.

![Screenshot from 2022-01-19 09-09-23](https://user-images.githubusercontent.com/13512097/150169952-33d769a4-28a9-4fbf-83f9-f130b430d638.png)

**Comment by mijorus** [comment]
The same issue happens when swiping up with three fingers to open the overview.

If you are on x11, so need to install [touchegg's Gnome extension](https://extensions.gnome.org/extension/4033/x11-gestures/)  to  enable gestures on X

**Comment by leviport** [comment]
Looks like this was fixed by https://github.com/pop-os/session/pull/55

@mijorus does it fix the same thing happening with that touchpad gesture as well?

**Comment by mijorus** [comment]
Fixed the issue with the keyboard shortcut, but not with the trackpad gesture (it's easy to see why as the patch basically just disables the shortcut)
