### ISSUE TITLE
Alt-tab popup doesn't disappear after selecting app

### ISSUE THREAD

**Issue by radiantone** [pop-os/gnome-shell-extension-pop-cosmic#310]
When using alt-tab and the app selector popup appears, selecting an app should switch to the app and the popup should disappear. This is how it has always worked, but with recent updates this has stopped working correctly and an extra escape or mouse click is needed to dismiss the alt-tab popup after the app is selected.

**Comment by leviport** [comment]
The selector disappears as expected for me on several machines.

Some background info might help:
- Which version of Pop!\_OS are you running?
- What kind of hardware are you running it on?
- What other Gnome Shell extensions do you have installed?

**Comment by radiantone** [comment]
I'm running the latest release (21.10) and its up to date. I did an OS refresh as well. I'm running on System76 oryxp5 laptop.
After about a month or two ago updating OS, the desktop started to experience lots of bugs. Just last week, triggering the workspaces would cause all my app UIs to disappear and I would have to reboot, however, that seems to have been fixed.

**Comment by radiantone** [comment]
https://user-images.githubusercontent.com/25509097/153685305-e72a29cf-bfee-4c23-8048-1cecb721081e.mp4

**Comment by radiantone** [comment]
In the above video the selector stays on screen until I hit escape or click mouse button which is either terrible design (if that's the new intention) or a bug because it never worked like that before.

**Comment by radiantone** [comment]
Here are my gnome extensions. Nothing crazy

['alt-tab-raise-first-window@system76.com', 'always-show-workspaces@system76.com', 'batteryiconfix@kylecorry31.github.io', 'desktop-icons@csoriano', 'pop-shell@system76.com', 'pop-shop-details@system76.com', 'system76-power@system76.com', 'ubuntu-appindicators@ubuntu.com', 'system-monitor@paradoxxx.zero.gmail.com', 'gnome-shell-screenshot@ttll.de', 'Resource_Monitor@Ory0n', 'ding@rastersoft.com', 'systeminfo@noctrl.eu', 'System_Monitor@bghome.gmail.com', 'tweaks-system-menu@extensions.gnome-shell.fifi.org', 'dash-to-dock@micxgx.gmail.com']

**Comment by radiantone** [comment]
It's dash-to-dock that is causing the problem.
