### ISSUE TITLE
Workspace View Broken

### ISSUE THREAD

**Issue by radiantone** [pop-os/gnome-shell-extension-pop-cosmic#311]
In recent updates, workspaces have either stopped working entirely or are broken for multi-monitor setup.
This has worked properly in previous release older than a couple months.

Currently, viewing workspaces will tile the open apps on the primary display, but the workspace mini screen selection widget is no longer visible. Furthermore, apps on additional monitors do not tile on those monitors. This is a regression from previous releases.

**Comment by radiantone** [comment]
Dash-to-dock gnome extension was causing this problem.

**Comment by 392781** [comment]
I just ran into this myself.  I wonder what is compatibility issue with the two.  Dash-to-dock is a recommended customization by Pop!_OS so it would be nice to see it fixed.
