### ISSUE TITLE
App grid takes up most of screen at 1366x768 resolution

### ISSUE THREAD

**Issue by rckmachado** [pop-os/gnome-shell-extension-pop-cosmic#314]
I'm sorry but this problem return in the last update :(

![Screenshot from 2022-02-21 08-42-56](https://user-images.githubusercontent.com/32842682/154953738-e8c23128-b225-46fe-a6f4-6d94bca3eb4d.png)

_Originally posted by @rickm00 in https://github.com/pop-os/cosmic/issues/264#issuecomment-1046816945_

**Comment by jacobgkau** [comment]
This is expected behavior as of https://github.com/pop-os/cosmic/pull/306. The app grid will display up to 7 columns and 3 rows when they fit; when they don't fit, the grid will shrink.

Your screen resolution is very low, so you will not have as much space on the screen. I'm not sure how much this should be considered a bug. It sounds like you're just wanting the icons to be smaller?

**Comment by jacobgkau** [comment]
We could perhaps increase the vertical margin to try and force 1366x768 displays down to only 2 rows of icons. The current margin worked well with 720p (see screenshot in https://github.com/pop-os/cosmic/pull/306#issuecomment-1029381725), but 1366x768 may be a more common resolution than 1280x720.

**Comment by rckmachado** [comment]
> This is expected behavior as of #306. The app grid will display up to 7 columns and 3 rows when they fit; when they don't fit, the grid will shrink.
> 
> Your screen resolution is very low, so you will not have as much space on the screen. I'm not sure how much this should be considered a bug. It sounds like you're just wanting the icons to be smaller?

This is a bug in the interface design, the library should adapt to the resolution, the problem had been reported and solved, they inserted a scroll bar and decreased the size of the display box, now in the last update this problem has returned. If there was an option to reduce the size of the icons, it would help a lot.

**Comment by rckmachado** [comment]
> We could perhaps increase the vertical margin to try and force 1366x768 displays down to only 2 rows of icons. The current margin worked well with 720p (see screenshot in [#306 (comment)](https://github.com/pop-os/cosmic/pull/306#issuecomment-1029381725)), but 1366x768 may be a more common resolution than 1280x720.

Agreed!

It is strange because this had been fixed, it had looked beautiful, adjusted the resolution, now it has returned.

**Comment by rickm00** [comment]
This also happens with the notification box display, when the dash is at the bottom, it overlaps, it looks very strange. I'm sorry, I'm a UX/UI designer and I notice these things a lot.
![Uploading Screenshot from 2022-02-21 15-42-03.png…]()

**Comment by rckmachado** [comment]
This also happens with the notification box display, when the dash is at the bottom, it overlaps, it looks very strange. I'm sorry, I'm a UX/UI designer and I notice these things a lot.

![Screenshot from 2022-02-21 15-42-03](https://user-images.githubusercontent.com/32842682/155011455-259f5a47-ccfd-4be9-be55-0655e0f4f0d0.png)

**Comment by jacobgkau** [comment]
> It is strange because this had been fixed, it had looked beautiful, adjusted the resolution, now it has returned.

The fix caused regressions for users of HiDPI displays (which are something System76 currently sells, unlike 1366x768 displays.) You can read https://github.com/pop-os/cosmic/pull/277 for more of the context.

> This also happens with the notification box display

The notification box would be a GNOME Shell component.

**Comment by rckmachado** [comment]
> > It is strange because this had been fixed, it had looked beautiful, adjusted the resolution, now it has returned.
> 
> The fix caused regressions for users of HiDPI displays (which are something System76 currently sells, unlike 1366x768 displays.) You can read #277 for more of the context.
> 
> > This also happens with the notification box display
> 
> The notification box would be a GNOME Shell component.

I see. Is there any possibility of future correction or will it really no longer be adjusted for lower resolutions?

**Comment by ghost** [comment]
Is there any fix progress for this bug?

**Comment by warthunder1969** [comment]
> Is there any fix progress for this bug?

I've got the same question as well. I can report it is definitely still an issue with Pop OS 22.04. UI looks fine at 1280x720 but is too oversized for 1366 x 768. If we could have the scale of the 1280x720 be used at the 1366 resolution that would solve the problem....

**Comment by Cealica** [comment]
Got myself the same bug too on a fresh install 22.04, but when i tried 720p it works just fine but in 768p the application just takes up a whole lot of space.
