### ISSUE TITLE
[Bug] Inconsistent behaviour of the `super`+`Q` shortcut 

### ISSUE THREAD

**Issue by bourquenoud** [pop-os/gnome-shell-extension-pop-cosmic#315]
Pressing `super`+`Q` has the expected behaviour of closing the focused window. However, it appears that sometimes this shortcut changes its behaviour, by bringing up the Cosmic Dock instead. Once the behaviour changes it doesn't go back to it's original behaviour for the entire session. Logging out and back in resolves the issue.

I was unable to find a reason for this and I can't reproduce the error. 

---
No conflicting custom shortcuts

`uname -a` :
```
Linux pop-os 5.15.23-76051523-generic #202202110435~1644952300~21.10~96763f1 SMP Tue Feb 15 19:52:40 U x86_64 x86_64 x86_64 GNU/Linux
```

Distribution :
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

```

**Comment by senntore** [comment]
I saw this fix on reddit, it happens because the shortcut conflict with another one in Dash to Dock(or similar extensions).
See https://www.reddit.com/r/pop_os/comments/ra3mtm/comment/hngyt75/

**Comment by bourquenoud** [comment]
Dash to Dock doesn't appear when listing the active extensions. However, it was present in `~/.local/share/gnome-shell/extensions.bak` (note the `.bak`).

I was unable to change any settings of the extension, as it wasn't active. I manually deleted the folder in `extensions.bak`. I'll update the issue if the problem disappeared.

**Comment by bourquenoud** [comment]
When typing `gnome-extensions list` dash-to-dock didn't appear. But it was listed by `gsettings`. There was in fact a shortcut collision.

The solution was to change the key binding, using the following command : 
```bash
gsettings set org.gnome.shell.extensions.dash-to-dock shortcut ['']
gsettings set org.gnome.shell.extensions.dash-to-dock shortcut-text \'\'
```

In my case I set the shortcut to nothing, but it is possible to change it to something else. For example to change it to ctrl+super+q :
```bash
gsettings set org.gnome.shell.extensions.dash-to-dock shortcut [\'\<Ctrl\>\<Super\>q\']
gsettings set org.gnome.shell.extensions.dash-to-dock shortcut-text \'\<Ctrl\>\<Super\>q\'
```
