### ISSUE TITLE
Application launcher and some additional suggestions

### ISSUE THREAD

**Issue by theredknight205** [pop-os/gnome-shell-extension-pop-cosmic#316]
## Application launcher takes more space so i cant access work spaces properly
*allow work spaces  to be accessed with application launcher when pressing (super+a) and allow launcher to open in overview so it would be easy to shift application from the launcher itself.
![Screenshot from 2022-03-08 10-52-28](https://user-images.githubusercontent.com/101165014/157171778-9f86a297-317c-4424-a5c5-d12b0866a677.png)
*

**Comment by mmstick** [comment]
You mean that you can't click on Workspaces? Or that the workspaces shortcut isn't working (super + d)?

**Comment by theredknight205** [comment]
The application is too big so it covers the workspaces so i can't put apps
directly on it

**Comment by cyrneko** [comment]
I'd love to see this adjustable/fixed, as having the menu this big on smaller, or lower resolution screens simply looks unnatural _(like the screen of my ThinkPad SL510)_

**Comment by leviport** [comment]
I think this is a duplicate of https://github.com/pop-os/cosmic/issues/314

We can reopen if I'm mistaken

**Comment by cyrneko** [comment]
> I think this is a duplicate of #314
> 
> We can reopen if I'm mistaken

Ah, my bad
I remember searching for "too big" and "size" not yielding results, so I opened another issue

Thanks for clearing me up! 👍
