### ISSUE TITLE
E: Unable to locate package pop-cosmic

### ISSUE THREAD

**Issue by johncaling40** [pop-os/gnome-shell-extension-pop-cosmic#32]
When running `sudo apt install pop-cosmic libpop-desktop-widget gnome-shell-extension-ubuntu-dock gnome-shell-extension-multi-monitors`, I get `E: Unable to locate package pop-cosmic`. How do I fix this?

**Comment by johncaling40** [comment]
I was able to fix by installing from source

**Comment by isrx** [comment]
Is there a better way to do it? rather than installing from source?
