### ISSUE TITLE
Backwards compatibility for toucheg.conf files that call `gesture()`

### ISSUE THREAD

**Issue by canadaduane** [pop-os/gnome-shell-extension-pop-cosmic#322]
The awesome PR #320 makes touchpad gestures aware of the "natural scrolling" setting and respect it in a sensible way. However, if the user has ever created a personal `touchegg.conf` file (e.g. previously done something like `cp /usr/share/touchegg/touchegg.conf ~/.config/touchegg`) then the update causes touch gestures to stop working.

One solution would be to continue to provide the `gesture()` function in a backwards-compatible way, so that "old" conf files (i.e. older than 10 days ago) will still work.

"Old" conf file can be compared with "new" with this diff: https://github.com/pop-os/touchegg/pull/5/files

Impacted people: https://www.reddit.com/r/pop_os/comments/tkdhrv/touchpad_gestures_stopped_working/

**Comment by jpttrssn** [comment]
Oh, bummer! Had not considered this. The only way to make this backwards compatible is to add the old interface back, while also keeping the new one. This would require maintaining two interfaces, which is never fun. The new interface is also simpler and arguably reduces the need to change the `touchegg.conf` in the future. I would also argue that if someone has their own `touchegg.conf` they are responsible for maintaining it.

That being said, I hear what you're saying and understand the problem. More than happy to make a patch if deemed necessary.

**Comment by jackpot51** [comment]
As of GNOME 42, org.gnome.Shell.Eval will no longer function by default. This means that custom touchegg configurations will already have to break in the next month as we release Pop 22.04, and there is nothing we can do to prevent this.

**Comment by canadaduane** [comment]
Understood, thanks.
