### ISSUE TITLE
Fractional scaling not working as intended.

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#33]

**Comment by philibertc** [comment]
Hello @DuttaAB-dev 
This is not a problem with the COSMIC gnome extension, which is just a kind of overlay.
Maybe you can publish this issue, with more description, on https://github.com/pop-os/pop/issues or on the GitLab of the Gnome project.

**Comment by DuttaAB-dev** [comment]
Okay sure i will, but as far i have seen, this issue only exists in pop os as in Ubuntu 21.04, fractional scaling works flawlessly.
