### ISSUE TITLE
[Suggestion] Add the ability to search applications on the Workspaces view back

### ISSUE THREAD

**Issue by rolaca11** [pop-os/gnome-shell-extension-pop-cosmic#337]
I really like it in the default GNOME and liked it in the older version of COSMIC. I don't want to disable COSMIC, because it has some nice features, but I'd still like to be able to search apps in the Workspaces view.

**Comment by leviport** [comment]
There is a discussion thread for this topic: https://github.com/pop-os/cosmic/discussions/95
