### ISSUE TITLE
Workspace switching to follow swipe gesture

### ISSUE THREAD

**Issue by spacekookie** [pop-os/gnome-shell-extension-pop-cosmic#338]
Something I'm used to from macOS is that switching between workspaces is a gradual animation that follows the gesture progress on the touchpad, instead of triggering a "oneshot" animation that completes independently of how far the fingers were moved across the touchpad.

I don't know if this is possible to implement in COSMIC or if the current behaviour is a limitation of GNOME but I wanted to suggest it as a feature anyway. The current behaviour feels a bit disorienting to me.

**Comment by spacekookie** [comment]
Oh I just noticed that Pop_OS does this now. Was this implemented or did something unrelated start working on my system? :thinking:

**Comment by leviport** [comment]
Yep, that was added in https://github.com/pop-os/session/pull/53

Thanks for following up, I had forgotten this issue was still open. I'll close it now since it was implemented.

**Comment by spacekookie** [comment]
@leviport thanks for making Pop_OS better :heart:
