### ISSUE TITLE
Allow user to disable Overlay (Super) key behavior in settings

### ISSUE THREAD

**Issue by TDuffinNTU** [pop-os/gnome-shell-extension-pop-cosmic#357]
Currently, users of arc menu have to manually edit extension.js to comment out the overlay_key function if they want to manually control the Super key's functionality (to open up the alternative menu). There's also other reasons a user may want to hand control of the Super Key to another app or extension while still using pop-Cosmic.

at the moment, you can change Super from either controlling the overlay menu, or showing the app tray, but not disable it altogether.

I could easily disable pop-cosmic, but this is just a QoL change that seems easy enough to accomplish :)

**Comment by atimeofday** [comment]
I second this.

Thank you so much for pointing me to the right file and lines to comment out! It's exactly what I needed.

**Comment by TDuffinNTU** [comment]
Closing as likely addressed with migration to Cosmic DE :)
