### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DCoder010** [pop-os/gnome-shell-extension-pop-cosmic#36]
1. It would be nice if the dynamic workspace could be switched to right since most of the users are right handed it feels natural dragging windows to the right than to the left
2. The dock on the bottom is empty on the left and right sides. So when you switch the position of the panel to the left or right of the screen the top and bottom looks empty which does not look good. So I would suggest to have something like automatic increase in dock size as the users put applications on the dock so that it wouldn't look weird when the dock is position to left or right of the screen. I believe this can be achieved by turning off the "Extend dock to edge of the screen option". Correct me if I am wrong
3. It would also be nice to have the application launcher on the dock(the 9 dots)  could be draggable in the dock to left or middle or right or anywhere according to users preference

**Comment by DuttaAB-dev** [comment]
The first feature is already in the works(Available in the settings with the TODO tag)

**Comment by mmstick** [comment]
Features already exist
