### ISSUE TITLE
Missing libc6 (2.33) and libgdk-pixbuf-2.0.0 (2.22.0)

### ISSUE THREAD

**Issue by ghost** [pop-os/gnome-shell-extension-pop-cosmic#37]
I was trying to install cosmic but it throws me this error
![Screenshot from 2021-05-04 13-15-33](https://user-images.githubusercontent.com/81704775/117043146-d6b58380-acda-11eb-84d7-b503323cd9c6.png)

i tried installing libc6 2.33, but it says that it will break locales-all.
![Screenshot from 2021-05-04 13-17-19](https://user-images.githubusercontent.com/81704775/117043345-19775b80-acdb-11eb-93f4-5c8e29a0fe5c.png)
What do i do from here? Also, i recently upgraded to 21.04 via the following command:
`pop-upgrade release update -f`

**Comment by DuttaAB-dev** [comment]
check if your repositories got upgraded. go to `/etc/apt/sources.list.d` and check individual repo files to see if the word groovy has been replaced with hirsute everywhere. After this run the command 
`sudo apt update && sudo apt upgrade`. Had the same issue and fixed it this way.. apparently the pop-upgrade fails to upgrade the repos.

**Comment by ghost** [comment]
Ok, i will try once I get to my laptop :)

Many thanks 😊

**Comment by stationaryStation** [comment]
![Screenshot from 2021-05-05 07-41-29](https://user-images.githubusercontent.com/81704775/117135763-63ad1b00-ad75-11eb-920e-20168d53b48d.png)
Well. Now I now can upgrade packages but now i get this error instead. What a mess :/

**Comment by ghost** [comment]
Many thanks, i finally can experience cosmic :D
