### ISSUE TITLE
Power settings goes back from "High Performance" to "Balanced" after restart (reboot)

### ISSUE THREAD

**Issue by ghost** [pop-os/gnome-shell-extension-pop-cosmic#377]
Hi, in the top right side of the desktop environment, the power settings has 3 options under it. When i choose "High Performance" it goes back to "Balanced" after i restart (reboot) the computer. Is there a way to save the state of this setting ?

**Comment by leviport** [comment]
That is expected at the moment. A feature request has been filed here: https://github.com/pop-os/system76-power/issues/263
