### ISSUE TITLE
[Feature request] The Workspaces view should be merged with the Launcher

### ISSUE THREAD

**Issue by PoignardAzur** [pop-os/gnome-shell-extension-pop-cosmic#386]
## Description

When you open the "Workspaces" view, there should be a text bar with a "Type to search apps, or type '?' for more options" placeholder text. Using any text input in the view should automatically focus the bar, write the text in it, and switch to the "Launcher" view (the view you get when pressing Super when your 'Settings > Desktop > Desktop Options > Super Key Action" config is set to "Launcher").

Additionally, "Workspaces" should be the default value of that config.

## Rationale

The 21.04 update of PopOS included a new pop-shell UI, where among other things, the "Activities" view was split into the "Workspaces" view and the "Applications" view. Additionally, a new "Launcher" view was created.

Before this, users who pressed the Super key would access the Activities view, which initially behaved like the current Workspaces view (`Super + D` to open it on 22.04); if they started typing the name of an application, the view would automatically display a list of applications filtered with the input text, like the current Applications view. This led to a single unified, discoverable workflow for both visualizing workspaces and opening new applications.

**This is no longer possible since the 21.04 update, which I believe is a mistake.** Typing text in the Workspaces view doesn't do anything anymore. The only workaround to get the previous behavior is to disable the Pop COSMIC extension, which is obviously not ideal (not discoverable, not actually supported, breaks some UI bits, etc).

This is a common complaint, eg:

- https://www.reddit.com/r/pop_os/comments/oatisv/can_i_disable_cosmic_if_not_can_i_downgrade_from/
- https://www.reddit.com/r/pop_os/comments/uqpy4j/i_hate_the_new_launcher_in_2204/
- https://www.reddit.com/r/pop_os/comments/11eejxr/where_to_submit_feature_requests/
- https://www.reddit.com/r/pop_os/comments/og9svk/comment/h4ie4l3/?utm_source=reddit&utm_medium=web2x&context=3

I believe that the PopOS team at the time thought that the "Activities -> Workspaces + Applications" split wasn't a regression, because there was a `Super+D` shortcut and a trackpad gesture added to access the Workspaces view; but the shortcut isn't very discoverable (I didn't know about it until I started writing this issue) and a lot of PopOS users don't have a trackpad.

And generally speaking, the behavior of "Show workspaces *and also* a search box" when the Super key is pressed just... feels better? I feel like it was a pretty good UI default, and changing it was an unforced downgrade; the fact that the previous UI was made mutually incompatible with the new launcher just makes me not use the new launcher.

There's probably a good design middle-ground to be found, for example "When you press super, the Workspaces picker appears on the right, and the Launcher box appears in the middle". Just don't make me choose between both and then handicap the option you prefer less. That felt like a pretty user-hostile move at the time (or at least user-deaf), and it's the only serious regression I've ever had in my use of PopOS.

**Comment by leviport** [comment]
There is already a discussion thread for this: https://github.com/pop-os/cosmic/discussions/95

**Comment by PoignardAzur** [comment]
I didn't know about that thread, sorry.

I also notice another issue at #85, so I'll post my thoughts there.
