### ISSUE TITLE
Ghost window appears while autotiling on Wayland

### ISSUE THREAD

**Issue by benuski** [pop-os/gnome-shell-extension-pop-cosmic#389]
Hello!

This is kind of strange, so I'll try to explain. Recently, on Pop on Wayland, I have been having an issue. When I open a window, it will occupy the left half of the screen. While I full screen it, it goes into the supertab mode, except that the other window besides my browser is "@!0,0.BDHF" Here is an image of what it looks like:

![image](https://user-images.githubusercontent.com/4992312/231595691-e97e8720-ff8b-49ae-b9b7-ecef0333d066.png)

I re-installed Pop to see if that would help fix it; when I just switched to the Wayland session, the error came back.

Thanks,

**Comment by leviport** [comment]
I think this might be a duplicate of https://github.com/pop-os/shell/issues/1608 

If that's what it is, they did find a workaround in the thread, and we have a PR open that should hopefully fix it by default.

**Comment by benuski** [comment]
> I think this might be a duplicate of [pop-os/shell#1608](https://github.com/pop-os/shell/issues/1608)
> 
> If that's what it is, they did find a workaround in the thread, and we have a PR open that should hopefully fix it by default.

that's what it seems to be, so i will follow along there. thanks!
