### ISSUE TITLE
Steam Games "not responding"

### ISSUE THREAD

**Issue by juan-lunarg** [pop-os/gnome-shell-extension-pop-cosmic#395]
![image](https://github.com/pop-os/cosmic/assets/114601453/266f3d48-e310-4b10-9869-4956c80959e4)

I've encountered this issue a few times when playing games on Pop-OS!. I get a pop up saying the game is not responding, but then I just have to wait a little bit and it works. I've only see this issue occur when starting up a title.

I'm able to easily reproduce the issue with [Team Fortress 2](https://store.steampowered.com/app/440/Team_Fortress_2/).

Note you will need to set `-novid` on the CLI for `Team Fortress 2` in order for the issue to appear.

![image](https://github.com/pop-os/cosmic/assets/114601453/a0af6350-b492-47bd-9074-1d30a6ec1152)

This issue isn't exclusive to TF2. It also occurs on other titles like [Frogun](https://store.steampowered.com/app/1575470/Frogun/).

![image](https://github.com/pop-os/cosmic/assets/114601453/201c761b-4b52-43bb-af37-06c4a7813c39)

I'm able to reproduce this issue on my `System76 Pangolin` with Pop!_OS 22.04 LTS

**Comment by juan-lunarg** [comment]
Closing since it's not really a big deal and doesn't happen on all titles. I am still curious what the issue is but I'll leave it for now.

**Comment by jacobgkau** [comment]
Hi, this would be unlikely to be related to the COSMIC GNOME Shell extension, which is what this repository is for. The general catch-all repository for issues not yet narrowed down to a component is https://github.com/pop-os/pop. Does the issue still occur if you open the Extensions app (green icon) and disable the `Pop COSMIC` extension? (This will cause some potentially-unwanted changes to your user interface until you turn it back on, but it would narrow down whether the extension is at fault.)

It's interesting setting the `-novid` option causes the issue-- doesn't that option just disable or skip intro videos in the game?

I would try running `top` in a terminal or opening System Monitor next time this happens to see if any processes are using up a large amount of CPU.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by juan-lunarg** [comment]
> It's interesting setting the -novid option causes the issue-- doesn't that option just disable or skip intro videos in the game?

Correct it just skips the intro valve video.

> Does the issue still occur if you open the Extensions app (green icon) and disable the Pop COSMIC extension?

The issue still occurs.

![image](https://github.com/pop-os/cosmic/assets/114601453/4e3fb14d-6948-459a-aa4b-74d360f53c23)

> I would try running top in a terminal or opening System Monitor next time this happens to see if any processes are using up a large amount of CPU.

![image](https://github.com/pop-os/cosmic/assets/114601453/289dda1e-ade5-424f-b77c-f243bfffff17)

I don't see any process using a large amount of CPU. `hl2_linux` uses about 5-7 percent it's fairly old game.
