### ISSUE TITLE
[Feature Request] XWayland Input Support

### ISSUE THREAD

**Issue by aarongerber** [pop-os/gnome-shell-extension-pop-cosmic#397]
Perhaps this is far removed from the work being done on this project or cosmic rust, but I noticed a plan to use XWayland on Cosmic Rust, and my hope is this will create improvements around input.

It has been a while since I have tried, but all documentation I've seen seems to indicate over and over that X11 has far more support for input simulation and manipulation. I'm not sure how XWayland compares, but every time I have wanted to modify input Wayland  has not supported what I have wanted to do: Changes to how my multi-button mouse works (simulating keys with button presses), or creating a switch behavior in Virt-Manager where I can send my mouse in to the VM by pressing two CTRL keys, or return control to my host OS. 

Please consider these implications, and improve this if at all possible in the switch to XWayland.

**Comment by RinLovesYou** [comment]
as an addendum, would love KDE like handling for global xwayland keybinds. As it stands it only works in other xwayland apps. Pretty essential for discord push to talk. If you implement this, make sure to include mouse buttons, as my push to talk has been mouse button 4 for years!

**Comment by aarongerber** [comment]
Wrong repo, will post in https://github.com/pop-os/cosmic-epoch/issues
