### ISSUE TITLE
Visual issue with favorites bar

### ISSUE THREAD

**Issue by bflanagin** [pop-os/gnome-shell-extension-pop-cosmic#4]
On my Gaze15 the bottom bar has a 2 to 3 pixel gap on left of the screen as well as between the bar and the application window. This might be by design, but the right hand side doesn't show the 2 to 3 pixel gap that is shown on the left which looks unbalanced. 

![Screenshot from 2021-04-06 16-32-25](https://user-images.githubusercontent.com/10382037/113782052-31b58400-96f7-11eb-9f80-9408ff98614e.png)

**Comment by isantop** [comment]
I also noticed this, and saw that it doesn't occur if the favorites bar runs along the left or right

**Comment by bflanagin** [comment]
Fixed in the latest revision 6d63096.

Will reopen if its seen again.
