### ISSUE TITLE
Dock appears briefly when unlocking screen when "Show Dock" is disabled

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-shell-extension-pop-cosmic#41]
This is a very minor bug, but I figured it was worth filing anyway. If I turn off the "Show Dock" setting in GCC > Desktop > Dock, the dock goes away as expected. However, I see it appear and disappear briefly after unlocking my screen.

Here are my dock settings, in case it's anything specific here that's making it happen:
![2021-05-11_09-57](https://user-images.githubusercontent.com/13512097/117847260-6a3d0600-b23f-11eb-9466-f432623d53bc.png)

**Comment by bflanagin** [comment]
Still happening in 0.1.0~1620831172~21.04~04072ab. Maybe its intentional?

**Comment by WatchMkr** [comment]
Appears fixed now. Closing.
