### ISSUE TITLE
(Feature Request) Frosted Glass Effect for semi-transparent windows

### ISSUE THREAD

**Issue by trigg** [pop-os/gnome-shell-extension-pop-cosmic#411]
"Frosted glass effect" Could optionally be expanded to work on all semi-transparent windows.

![screenshot-2024-02-20-20-59-50](https://github.com/pop-os/cosmic/assets/535772/2000a4dc-3cd8-4b51-b490-438d97e9f6e0)

Also - arguably- the interface frosted effect should work on other Layer-Shell semi-transparent windows

![screenshot-2024-02-20-21-01-56](https://github.com/pop-os/cosmic/assets/535772/1ef8deb9-c1f6-4ad4-b324-8cd6cad63443)

**Comment by mmstick** [comment]
This repository is a gnome shell extension. That said, effects like blur are already planned for cosmic-epoch
