### ISSUE TITLE
arch linux: system icon are just black

### ISSUE THREAD

**Issue by woodgear** [pop-os/gnome-shell-extension-pop-cosmic#419]
![screenshot-2024-07-24-07-52-17](https://github.com/user-attachments/assets/388a3e99-e8c9-49ab-a144-8f544afea099)

6.9.6-arch1

**Comment by abitofevrything** [comment]
@woodgear did this resolve itself for you? I'm encountering the same issue on the latest version of COSMIC available from the AUR (`cosmic-session 1.0.0.alpha.1.r1.g4df7261-1`).

Were there any steps you took to fix it?

**Comment by abitofevrything** [comment]
For anyone coming across this issue: you need to install vulkan drivers on your system.

See https://www.reddit.com/r/pop_os/comments/1cqm37h/comment/l3sa889.
