### ISSUE TITLE
Feature Request - libportal support for cosmic

### ISSUE THREAD

**Issue by bkahlerventer** [pop-os/gnome-shell-extension-pop-cosmic#433]
I use pop-os in a multi-laptop layout multi-screen layout and need to have libportal support for input-leap.  

https://github.com/input-leap/input-leap 

input-leap does support libei for handling wayland input, it also depends on libportal for input-capture

i   libportal-dev                                                                                            - Flatpak portal library (development files)
p   libportal-doc                                                                                            - Flatpak portal library (documentation)
i A libportal-gtk3-1                                                                                         - Flatpak portal library for GTK 3 GUIs
i   libportal-gtk3-dev                                                                                       - Flatpak portal library (development files for GTK 3)
i A libportal-gtk4-1                                                                                         - Flatpak portal library for GTK 4 GUIs
i   libportal-gtk4-dev                                                                                       - Flatpak portal library (development files for GTK 4)
p   libportal-qt5-1                                                                                          - Flatpak portal library for Qt 5 GUIs
p   libportal-qt5-dev                                                                                        - Flatpak portal library (development files for Qt 5)
p   libportal-tests-gtk3                                                                                     - Flatpak portal library (test program for GTK 3)
p   libportal-tests-gtk4                                                                                     - Flatpak portal library (test program for GTK 4)
p   libportal-tests-qt5                                                                                      - Flatpak portal library (test program for Qt)
i A libportal1                                                                                               - Flatpak portal library - non-GUI part

**Comment by mmstick** [comment]
We already use ashpd: https://crates.io/crates/ashpd

**Comment by bkahlerventer** [comment]
This means that input-leap/Barrier/Synergy/etc. projects without any real support on Cosmic, leaving me unable to use cosmic as a consequence.  The support for libportal are really a requirement for me... I'm really sorry to see it not being supported.  I will this dump Pop-os & cosmic and search for a new desktop.

**Comment by mmstick** [comment]
libportal is a client library. ashpd already exists for Rust applications.

**Comment by bkahlerventer** [comment]
true, but none of the shared KM apps use that library, neither is any of those apps written in Rust.  Which will probably set dev of an equivalent back several years.  This is not useful in my circumstance.  The libportal route would have improved the interop until development can take place.  Appreciate the direct refusal of the feature, as I now can hunt for an alternative.

**Comment by mmstick** [comment]
It doesn't matter what library a client uses. They communicate to the same portal daemons. I think you're confusing libportal with the actual xdg portal spec. COSMIC implements its own portals, and whether an application uses libportal or ashpd doesn't matter. Rust applications use ashpd. C applications use libportal. COSMIC applications use ashpd.

**Comment by ctrlaltprocrastinate** [comment]
As far as i understand, input-leap requires libportal-0.8 whereas Pop!OS only provides v0.7.1
