### ISSUE TITLE
Laptop monitor goes bogus on first HDMI connection

### ISSUE THREAD

**Issue by jon011235** [pop-os/gnome-shell-extension-pop-cosmic#445]
I connected a screen via HDMI and the following happened:
![signal-2024-11-25-172641](https://github.com/user-attachments/assets/7525a207-064b-4901-8b0c-ecfdb2cb1ac0)
![signal-2024-11-25-172644](https://github.com/user-attachments/assets/3db36540-89d7-4bd4-93f3-f5e4d02f2f6e)

It also did not go away after going over it with the mouse (which works for the dock just being blank)

After plugging HDMI out and in again it worked like a charm

**Comment by leviport** [comment]
This looks similar to https://github.com/pop-os/cosmic-comp/issues/499

Also, https://github.com/pop-os/cosmic-epoch would be the correct repo for COSMIC DE bug reports, not this one. This is "old COSMIC".
