### ISSUE TITLE
Don't hide windows in Applications view

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-shell-extension-pop-cosmic#47]
When entering the Applications menu, all visible windows are hidden. This seems left over from stock GNOME using the wallpaper as the app grid background.

Because COSMIC uses an opaque background for the app grid, we end up with two transitions, one to the wallpaper, and another to the opaque background. The first is unnecessary; the opaque background should just fade in over the windows.

This is especially evident when opening the app grid over a maximized window:

https://user-images.githubusercontent.com/7199422/119354571-783c4f00-bc61-11eb-9ca9-b9cb72ac1c4b.mp4

**Comment by ids1024** [comment]
After several changes to the behavior here, I believe this is addressed now. Closing.
