### ISSUE TITLE
Workspaces overview: should up and down arrows change workspaces?

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-shell-extension-pop-cosmic#48]
Binding different hotkeys in different views might require some pretty big modifications to Gnome, but I think being able to look through my workspaces with my arrow keys (maybe also J and K?) while I'm in the workspaces overview. PgUp/PgDn currently do what I'm referring to though, so maybe that's good enough?

**Comment by ids1024** [comment]
> Binding different hotkeys in different views might require some pretty big modifications to Gnome

Luckily this doesn't seem to be too difficult.

I don't recall seeing this issue earlier, but I guess it's much the same as https://github.com/pop-os/cosmic/issues/141. I think I'll close it since that is more general (also posing the question of whether other bindings might be useful).
