### ISSUE TITLE
Clock isn't centered when dock is set to left/right side

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-shell-extension-pop-cosmic#57]
The clock's centering currently shifts based on which side of the screen the dock is on:

https://user-images.githubusercontent.com/7199422/119859875-0408e200-bed3-11eb-855a-aa5366edb527.mp4

The clock should always be at the center of the physical display (it's obvious when it's off-center on laptops with centered webcams.)

**Comment by ids1024** [comment]
(Closed) upstream issue: https://github.com/micheleg/dash-to-dock/issues/1312, see also https://github.com/micheleg/dash-to-dock/issues/1373.

The first issue there links an upstream Gnome Shell commit: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/cd0af33947f8eb73a163ecef975728988ab51549

Apparently it's intentional that the clock is centered with respect to a full screened window.

Not sure if there would be any difficulty overriding that behavior in a shell extension.

**Comment by jacobgkau** [comment]
Didn't realize this was expected behavior in GNOME, might need input from UX then. @maria-komarova Do you have any thoughts on this?

This off-centering doesn't happen when auto-hide is enabled (because the dock hides when a window is maximized):

https://user-images.githubusercontent.com/7199422/119989714-b8af0c00-bf84-11eb-908a-a3b723797314.mp4

I understand the logic now, but it doesn't really look better to me centered to the maximized window instead of the physical display. Some apps don't have centered titles in their headerbars, so nothing really lines up anyway:

![Screenshot from 2021-05-28 07-20-36](https://user-images.githubusercontent.com/7199422/119990158-3ecb5280-bf85-11eb-9c10-cc92c1ab3c1a.png)

And when a window's not maximized, the result is being uncentered relative to the other content in the top bar. I suppose the result is centered to a default Pop Shell tree:

![Screenshot from 2021-05-28 07-23-22](https://user-images.githubusercontent.com/7199422/119990529-aaadbb00-bf85-11eb-9859-a25bb876546d.png)

**Comment by maria-komarova** [comment]
Didn't know that was the default behavior either. But to be honest, centering the clock relative to the tree or to the window looks more polished to my eye. I think it is more about visual symmetry than about the actual one there. When it is actually centered it looks less symmetrical and more like things do not align. So I'd stick to the default centering.

**Comment by jacobgkau** [comment]
I think what makes it look off the most is, like I said, the webcam on laptops, which is going to be physically centered regardless:

![IMG_20210528_085737](https://user-images.githubusercontent.com/7199422/120003339-e1d69900-bf92-11eb-943b-fd5fc59cd8bf.jpg)

But I'll close this for now since it's intentional.

**Comment by maria-komarova** [comment]
You are right about the camera. I'll keep that in mind and we can revisit it later.
