### ISSUE TITLE
Applications show underneath window spread

### ISSUE THREAD

**Issue by bflanagin** [pop-os/gnome-shell-extension-pop-cosmic#6]
![Screenshot from 2021-04-06 16-30-23](https://user-images.githubusercontent.com/10382037/113783189-fd42c780-96f8-11eb-9d27-8b245ddaacf6.png)

## Issue: 
Applications view shows underneath windows in spread view 

## How to trigger bug:

Using the buttons on the top bar click "Applications" then "Workspaces." The applications disappear but the windows aren't shown. Clicking "Workspaces" again will bring it back out of spread view as expected. Click "Workspaces" once more  and the error is presented.
You can also trigger the issue using the super key after going through the first steps listed above. Replacing the last step with the windows key.

The issue doesn't happen using the icon in the bottom bar.

**Comment by jackpot51** [comment]
Probably fixed by https://github.com/pop-os/cosmic/commit/272516343364bbdca04696ecd1951585396c3aad, open if it is not
