### ISSUE TITLE
Dock covers up workspace switcher

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-shell-extension-pop-cosmic#63]
This seems like the opposite of https://github.com/pop-os/cosmic/issues/56. I'm not yet sure what causes one to occur instead of the other, but I've currently got a boot where the workspace switcher is not moving over to give the dock space:

![Screenshot from 2021-06-01 10-09-39](https://user-images.githubusercontent.com/7199422/120357717-fb455100-c2c2-11eb-82c0-b535da3038af.png)

**Comment by Avendattor** [comment]
I have same problem.

Found way to reproduce:

1. Alt + F2, type "r" then Enter
2. There is no reserved space for dock

Found way to fix: 
1. Super + Esc (lock screen)
2. Unlock screen 
3. Reserve space for dock is OK

**Comment by ids1024** [comment]
This appears to happen when the cosmic-dock extension loads before cosmic. https://github.com/pop-os/cosmic/pull/173 seems to fix it.
