### ISSUE TITLE
Applications / Workspaces should activate their respective view when toggling between them.

### ISSUE THREAD

**Issue by bflanagin** [pop-os/gnome-shell-extension-pop-cosmic#7]
pop-cosmic:
  Installed: 0.1.0~1617742728~21.04~e984676
  Candidate: 0.1.0~1617742728~21.04~e984676
  Version table:
 *** 0.1.0~1617742728~21.04~e984676 1001

When you press the Applications button Applications are displayed, however if you switch to Workspaces using the button in the dash it goes back to your desktop instead of switching to the Workspaces view. The reverse is also true.

Oddly if you use the two options in the top bar the interface seems to attempt to switched to the mode requested but fails, requiring you to click the option a second time for the items or Workspaces to show.

https://user-images.githubusercontent.com/10382037/113872242-56524000-9779-11eb-8cc9-f6626263e036.mp4

**Comment by jackpot51** [comment]
Probably fixed by https://github.com/pop-os/cosmic/commit/272516343364bbdca04696ecd1951585396c3aad and https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/commit/eee2cc1aafed7b5c27226ca670edc78fd7c80a56, reopen if not
