### ISSUE TITLE
The launcher can not search for apps installed using wine(PlayOnLinux)

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#72]
The said apps have their respective entries in the gnome apps menu and are searchable through the gnome search bar.

**Comment by DuttaAB-dev** [comment]
The launcher is unable to search for the apps which were installed using PlayOnLinux. All of the said apps have their respective entries in the gnome apps menu and are searchable from there.

**Comment by ids1024** [comment]
Are those are provided through `~/.local/share/applications`? Though it seems it does search there, and it seems to work for me (but the `.desktop` files I have there aren't from PlayOnLinux).

**Comment by DuttaAB-dev** [comment]
> Are those are provided through `~/.local/share/applications`? Though it seems it does search there, and it seems to work for me (but the `.desktop` files I have there aren't from PlayOnLinux).

Yes, the .desktop files are under `/home/devops/.local/share/applications/wine/Programs`.

**Comment by blakeridgway** [comment]
I have Guild Wars 2 installed via PlayOnLinux and I am able to search for it through the Pop Launcher.

Located at  `~/.local/share/applications/wine/Programs` for the installation of Guild Wars 2 for myself.

**Comment by ids1024** [comment]
Thanks for the feedback. It looks like it's searching `~/.local/share/applications` but isn't recursively searching subdirectories.
