### ISSUE TITLE
When upgrade from old PopOS - libpop-desktop-widget : Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2

### ISSUE THREAD

**Issue by wellington1993** [pop-os/gnome-shell-extension-pop-cosmic#78]
After failed, terrible upgrade from old PopOS to 21.04.
I`m trying to fix apt sources and packages dependencies. 

When I try to reinstall the gnome-control-center, essential for the "cosmic" i have that problem:
```
Os pacotes a seguir têm dependências desencontradas:
 libpop-desktop-widget : Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
```

Full log:
```
○ sudo apt install --reinstall gnome-control-center\*
[sudo] senha para wellington: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Note, selecting 'gnome-control-center-data' for glob 'gnome-control-center*'
Note, selecting 'gnome-control-center' for glob 'gnome-control-center*'
Note, selecting 'gnome-control-center-faces' for glob 'gnome-control-center*'
Note, selecting 'gnome-control-center-dev' for glob 'gnome-control-center*'
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 libpop-desktop-widget : Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

```

If someone help me to fix the libc6 dependency will be possible to fix many other packages.
Someone could help me with that or provide tips, specially how to fix the apt sources list? 

Thanks!

**Comment by DuttaAB-dev** [comment]
Can you please try out this fix I mentioned in #37 and see if it works?

**Comment by wellington1993** [comment]
I can`t upgrade some packages from Groove to hirsute:
https://gist.github.com/wellington1993/86510dfc1066ee4aa1b594f402fd9f09

Thanks!

**Comment by DuttaAB-dev** [comment]
> I can`t upgrade some packages from Groove to hirsute:
> https://gist.github.com/wellington1993/86510dfc1066ee4aa1b594f402fd9f09
> 
> Thanks!

Yeah, that's a known issue with pop upgrade. It fails to upgrade the repos to hirsute. You need to manually upgrade them, as mentioned in that fix.

**Comment by wellington1993** [comment]
Thanks @DuttaAB-dev 

I`m trying to manually upgrade, I've upgrade some libc6* and dependencies.
And added a ubuntu hirsute to custom sources.

Now appears to be possible to fix the other packages:
https://gist.github.com/wellington1993/740a0c3e0aca7989bf14c9fadf99b622

Did you know when I can found a list of non default ubuntu/debian packages used in PopOS?
I want to reinstall the PopOS custom software lost in the failed upgrade process. 

Thanks!

**Comment by DuttaAB-dev** [comment]
> Thanks @DuttaAB-dev
> 
> I`m trying to manually upgrade, I've upgrade some libc6* and dependencies.
> And added a ubuntu hirsute to custom sources.
> 
> Now appears to be possible to fix the other packages:
> https://gist.github.com/wellington1993/740a0c3e0aca7989bf14c9fadf99b622
> 
> Did you know when I can found a list of non default ubuntu/debian packages used in PopOS?
> I want to reinstall the PopOS custom software lost in the failed upgrade process.
> 
> Thanks!

If you have all the Pop!_OS repos enabled, you can try running `sudo apt install pop-desktop` and see if it works.

**Comment by wellington1993** [comment]
@DuttaAB-dev Related problems:
https://github.com/pop-os/pop/issues/1727

@DuttaAB-dev I will try `sudo apt install pop-desktop` again.
But could you share the /etc/apt/ files used in PopOS cosmic.
Because now in apt, I have a merge between Ubuntu and PoPOS, and a merge beeteen hirsute and old version.
I want to normalize that files.

Thanks!

**Comment by DuttaAB-dev** [comment]
[apt.zip](https://github.com/pop-os/cosmic/files/6711806/apt.zip)
Here is all that I have in my /etc/apt/ directory. Feel free to use that to recover your system, just dont judge my software choices.
And also, can you please do the same yourself for your system as well? So that I can better understand the issue that you are facing.

**Comment by wellington1993** [comment]
@DuttaAB-dev Thanks!

I have progress, now, only that packages appears to be in conflict:

```c
wellington@pop-os ~$ sudo apt upgrade                                                                                                               
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os pacotes a seguir serão mantidos em suas versões atuais:
  fwupd libkpathsea6 libptexenc1 libsynctex2 libtexlua53 libtexluajit2 mariadb-backup mariadb-client mariadb-plugin-connect
  mariadb-plugin-cracklib-password-check mariadb-plugin-gssapi-client mariadb-plugin-gssapi-server mariadb-plugin-mroonga mariadb-plugin-oqgraph
  mariadb-plugin-rocksdb mariadb-plugin-spider mariadb-server plymouth plymouth-label plymouth-theme-spinner plymouth-theme-ubuntu-text
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-theme-switcher libs76-hidpi-widget mozc-server pop-shell-shortcuts
  pop-shop system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 20 revertidos, 0 a serem removidos e 21 não atualizados.
É preciso baixar 22,2 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] 
```

The other details appears to be direct related to the cosmic changes. 

Thanks!

**Comment by DuttaAB-dev** [comment]
After completing this upgrade, can you run `sudo apt update && sudo apt upgrade` again and then share the output?

**Comment by wellington1993** [comment]
@DuttaAB-dev After the upgrade cited before I've got a loop, because de dist-upgrade command change the roll backed packages to another versions again. 

Now I'm trying to equalize my/etc/apt files with the files provided by you.
And I will try again and share the results here soon. 

Thanks!

**Comment by wellington1993** [comment]
@DuttaAB-dev I will need to fix some hings in the try of merge the my apt files with your yours.

For example:

```c
E: Falhou ao buscar https://linux.teamviewer.com/deb/dists/stable/InRelease  403  Forbidden [IP: 2600:9000:21ed:c800:1c:3aaa:b100:93a1 443]
E: The repository 'https://linux.teamviewer.com/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Falhou ao buscar https://linux.teamviewer.com/deb/dists/preview/InRelease  403  Forbidden [IP: 2600:9000:21ed:c800:1c:3aaa:b100:93a1 443]
E: The repository 'https://linux.teamviewer.com/deb preview InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli.github.com/packages hirsute InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY C99B11DEB97541F0
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.docker.com/linux/ubuntu hirsute InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 7EA0A9C3F273FCD8
W: Erro GPG: https://brave-browser-apt-nightly.s3.brave.com stable InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0B31DBA06A8A26F9
E: The repository 'https://brave-browser-apt-nightly.s3.brave.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Erro GPG: https://brave-browser-apt-release.s3.brave.com stable InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY A8580BDC82D3DC6C
E: The repository 'https://brave-browser-apt-release.s3.brave.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
...

**Comment by DuttaAB-dev** [comment]
> @DuttaAB-dev I will need to fix some hings in the try of merge the my apt files with your yours.
> 
> For example:
> 
> ```c
> E: Falhou ao buscar https://linux.teamviewer.com/deb/dists/stable/InRelease  403  Forbidden [IP: 2600:9000:21ed:c800:1c:3aaa:b100:93a1 443]
> E: The repository 'https://linux.teamviewer.com/deb stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Falhou ao buscar https://linux.teamviewer.com/deb/dists/preview/InRelease  403  Forbidden [IP: 2600:9000:21ed:c800:1c:3aaa:b100:93a1 443]
> E: The repository 'https://linux.teamviewer.com/deb preview InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli.github.com/packages hirsute InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY C99B11DEB97541F0
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.docker.com/linux/ubuntu hirsute InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 7EA0A9C3F273FCD8
> W: Erro GPG: https://brave-browser-apt-nightly.s3.brave.com stable InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0B31DBA06A8A26F9
> E: The repository 'https://brave-browser-apt-nightly.s3.brave.com stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: Erro GPG: https://brave-browser-apt-release.s3.brave.com stable InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY A8580BDC82D3DC6C
> E: The repository 'https://brave-browser-apt-release.s3.brave.com stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> ...

You will have to remove `teamviewer.list` , `brave-browser-release.list` and `brave-browser-nightly.list` from your `/etc/apt/sources.list.d` as those repos were created in my system and thus their GPG files are absent in yours.
Try running sudo apt update again after deleting them.

**Comment by wellington1993** [comment]
@DuttaAB-dev Already deleting the extra sources, as suggested. 
But taking care about that related software already installed in the machine. 
I will share update/upgrade results soon. 

Thanks!

**Comment by wellington1993** [comment]
@DuttaAB-dev `apt list --upgradeable` results:

https://gist.github.com/wellington1993/b3a0b64fae1323fbf64c6b0ba1d8f31a

**Comment by wellington1993** [comment]
@DuttaAB-dev `apt upgrade` results:

https://gist.github.com/wellington1993/c3057dcd1eefea50929e9f5ccd231c9f

**Comment by wellington1993** [comment]
@DuttaAB-dev Curious information, packages will be reverted:

```c
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-theme-switcher libs76-hidpi-widget mozc-server pop-shell-shortcuts
  pop-shop system76-power ubuntu-drivers-common

```

Thanks!

**Comment by wellington1993** [comment]
@DuttaAB-dev Not fine yet:

```
A descompactar pipewire-bin (0.3.30-2~ubuntu21.04) sobre (0.3.24-3) ...
dpkg: aviso: não foi possível apagar o directório antigo '/etc/pipewire/media-session.d': Diretório não vazio
dpkg: aviso: não foi possível apagar o directório antigo '/etc/pipewire': Diretório não vazio
A seleccionar pacote anteriormente não seleccionado pipewire-pulse.
A preparar para desempacotar .../pipewire-pulse_0.3.30-2~ubuntu21.04_amd64.deb ...
A descompactar pipewire-pulse (0.3.30-2~ubuntu21.04) ...
A preparar para desempacotar .../pipewire_0.3.30-2~ubuntu21.04_amd64.deb ...
A descompactar pipewire:amd64 (0.3.30-2~ubuntu21.04) sobre (0.3.24-3) ...
dpkg: problemas com dependências impedem a configuração de pipewire:amd64:
 pipewire:amd64 depende de pipewire-bin (= 0.3.30-2~ubuntu21.04); porém:
  Pacote pipewire-bin não está configurado ainda.

dpkg: erro ao processar o pacote pipewire:amd64 (--configure):
 problemas de dependência - deixando desconfigurado
Nenhum relatório apport escrito pois a mensagem de erro indica que é um erro de seguimento de um erro anterior.
                                                                                                               Erros foram encontrados durante o proc
essamento de:
 pipewire:amd64
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
wellington@pop-os:~/Documents/upgrade/help 
 $ sudo apt upgrade                                                                                                                            100 ↵
[sudo] senha para wellington: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Você pode querer executar 'apt --fix-broken install' para corrigí-los.
Os pacotes a seguir têm dependências desencontradas:
 gstreamer1.0-pipewire : Depende: pipewire (= 0.3.24-3) mas 0.3.30-2~ubuntu21.04 está instalado
                         Depende: libpipewire-0.3-0 (= 0.3.24-3) mas 0.3.30-2~ubuntu21.04 está instalado
 pipewire-pulse : Depende: pipewire-media-session mas não está instalado
E: Dependências desencontradas. Tente 'apt --fix-broken install' sem nenhum pacote (ou especifique uma solução).
```

**Comment by wellington1993** [comment]
Something related to `gnome-shell`, `pipewire-pulse`, `gstreamer1.0-pipewire` and `pipewire-media-session` not fine yet:

```
Os pacotes a seguir têm dependências desencontradas:
 gnome-shell : Depende: gstreamer1.0-pipewire (>= 0.3.10) mas não será instalado
 pipewire-pulse : Depende: pipewire-media-session mas não será instalado
```

@DuttaAB-dev

**Comment by wellington1993** [comment]
Trying:

```
 $ sudo apt --fix-broken install
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Corrigindo dependências... Pronto
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libperl5.30 libpython2.7 perl-modules-5.30
Utilize 'sudo apt autoremove' para os remover.
The following additional packages will be installed:
  gstreamer1.0-pipewire pipewire-media-session
Os NOVOS pacotes a seguir serão instalados:
  pipewire-media-session
Os pacotes a seguir serão atualizados:
  gstreamer1.0-pipewire
1 pacotes atualizados, 1 pacotes novos instalados, 0 a serem removidos e 743 não atualizados.
61 pacotes não totalmente instalados ou removidos.
É preciso baixar 0 B/152 kB de arquivos.
Depois desta operação, 396 kB adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] 
```

**Comment by wellington1993** [comment]
@DuttaAB-dev It`s not being easy:

```c
wellington@pop-os:~/Documents/upgrade/help 
 $ sudo dpkg -i /var/cache/apt/archives/libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb                                             2 ↵
(Lendo banco de dados ... 891996 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb ...
A descompactar libgranite-common (6.0.0+r2063+pkg118~daily~ubuntu6.1) sobre (5.5.0-1) ...
dpkg: erro ao processar o arquivo /var/cache/apt/archives/libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb (--install):
 a tentar sobre-escrever '/usr/share/metainfo/granite.appdata.xml', que também está no pacote libgranite5:amd64 5.5.0-1
A processar 'triggers' para hicolor-icon-theme (0.17-2) ...
Erros foram encontrados durante o processamento de:
 /var/cache/apt/archives/libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb
wellington@pop-os:~/Documents/upgrade/help 
 $ sudo dpkg --force-all -i /var/cache/apt/archives/libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb                                 1 ↵
(Lendo banco de dados ... 891996 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../libgranite-common_6.0.0+r2063+pkg118~daily~ubuntu6.1_all.deb ...
A descompactar libgranite-common (6.0.0+r2063+pkg118~daily~ubuntu6.1) sobre (5.5.0-1) ...
dpkg: aviso: a ultrapassar problema porque --force está activo: 
dpkg: aviso: a tentar sobre-escrever '/usr/share/metainfo/granite.appdata.xml', que também está no pacote libgranite5:amd64 5.5.0-1
Configurando libgranite-common (6.0.0+r2063+pkg118~daily~ubuntu6.1) ...
A processar 'triggers' para hicolor-icon-theme (0.17-2) ...
```

...

**Comment by wellington1993** [comment]
I can't  go ahead. I get the same result every time `sudo apt upgrade` or `sudo apt upgrade -o Dpkg::Options::="--force-all`:

https://gist.github.com/wellington1993/1db8555884ce3e78fce17bd72846c27c

@DuttaAB-dev

**Comment by DuttaAB-dev** [comment]
> Trying:
> 
> ```
>  $ sudo apt --fix-broken install
> Lendo listas de pacotes... Pronto
> Construindo árvore de dependências... Pronto
> Lendo informação de estado... Pronto        
> Corrigindo dependências... Pronto
> Os seguintes pacotes foram instalados automaticamente e já não são necessários:
>   libperl5.30 libpython2.7 perl-modules-5.30
> Utilize 'sudo apt autoremove' para os remover.
> The following additional packages will be installed:
>   gstreamer1.0-pipewire pipewire-media-session
> Os NOVOS pacotes a seguir serão instalados:
>   pipewire-media-session
> Os pacotes a seguir serão atualizados:
>   gstreamer1.0-pipewire
> 1 pacotes atualizados, 1 pacotes novos instalados, 0 a serem removidos e 743 não atualizados.
> 61 pacotes não totalmente instalados ou removidos.
> É preciso baixar 0 B/152 kB de arquivos.
> Depois desta operação, 396 kB adicionais de espaço em disco serão usados.
> Você quer continuar? [S/n] 
> ```

You should continue with this here and then gain apt upgrade.

**Comment by DuttaAB-dev** [comment]
Can you send me your /etc/apt/ as a zip so that I can check if everything is alright?

**Comment by wellington1993** [comment]
@DuttaAB-dev Good idea, I will pack my /etc/apt in a zip file and send to you soon. 

Now I'm testing:
https://gist.github.com/wellington1993/bcfa9efb1c2548cae9eee4912d2e69f2

Thanks!

**Comment by wellington1993** [comment]
@DuttaAB-dev Before I send the ZIP, just to leave recorded, that are the packages asked to upgrade or remove every time:

```
└─[1] <> sudo apt upgrade
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify fwupd gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-desktop-widget libpop-theme-switcher libpop-upgrade-gtk
  libs76-hidpi-widget mozc-server pop-shell-shortcuts pop-shop pop-upgrade popsicle popsicle-gtk system76-firmware-daemon system76-oled
  system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 28 revertidos, 0 a serem removidos e 0 não atualizados.
É preciso baixar 1.500 kB/30,7 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] 

```

Thanks!

**Comment by wellington1993** [comment]
**APT:** [apt.zip](https://github.com/pop-os/cosmic/files/6719043/apt.zip)

@DuttaAB-dev My APT config files. 

apt upgrade result:
```
% sudo apt upgrade                                                                                                                21-06-25 - 19:24:30
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify fwupd gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-desktop-widget libpop-theme-switcher libpop-upgrade-gtk
  libs76-hidpi-widget mozc-server mozc-utils-gui pop-shell-shortcuts pop-shop pop-upgrade popsicle popsicle-gtk system76-firmware-daemon
  system76-oled system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 29 revertidos, 0 a serem removidos e 0 não atualizados.
É preciso baixar 1.500 kB/31,4 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] 

```

Thanks!

**Comment by DuttaAB-dev** [comment]
My friend,you have a lot of duplicates and a lot, lot of groovy stuff in your repos. Can you please wait for a few hours as it's way too late here in India😅

**Comment by DuttaAB-dev** [comment]
Okay well I have completely fixed your apt directory so hopefully it works this time. Here is the zip file:-
[apt.zip](https://github.com/pop-os/cosmic/files/6719648/apt.zip)

You must completely replace your current /etc/apt directory with the one I have provided, for this to work, and then run `sudo apt update` and `sudo apt upgrade`. Do not forget to backup your existing apt directory as a zip file first. Also, you might have to re-add some of the repos of the software you used, like git cli, as their gpg files are missing.

**Comment by wellington1993** [comment]
@DuttaAB-dev Many thanks! You are so helpful!

I'm trying to use that apt files.

**Comment by wellington1993** [comment]
**New apt:** 
[apt.zip](https://github.com/pop-os/cosmic/files/6723061/apt.zip)

100% fine the packages and sources.
And about Cosmic... 90% but I think is not related to the packages directly...

Thanks so much @DuttaAB-dev!

**Comment by wellington1993** [comment]
Closed with @DuttaAB-dev help! Thanks!

**Comment by DuttaAB-dev** [comment]
> @DuttaAB-dev Many thanks! You are so helpful!
> 
> I'm trying to use that apt files. 
> 
> 
> 

Glad that it worked! 😊
