### ISSUE TITLE
Apps Wall > Change the background color to solid matching the design

### ISSUE THREAD

**Issue by isantop** [pop-os/gnome-shell-extension-pop-cosmic#8]
The designs for COSMIC include a solid color background for the App Wall. Currently the background is the desktop wallpaper (darkened to aid separation from icons)

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/cosmic/commit/5e7a3399fc6b320e4974a93c041d6db429dbb85e and https://github.com/pop-os/gtk-theme/commit/e747d6829a1154672324af21dbc551c0de8c9512
