### ISSUE TITLE
Search bar no longer suggesting user apps

### ISSUE THREAD

**Issue by nigurr** [pop-os/gnome-shell-extension-pop-cosmic#83]
Hi,

Since last update, search apps no longer suggesting any user apps.
I can see the apps in Show Applications but not in search anymore
It's only suggesting system apps and default apps.

Any help is appreciated.

Info: 
21.04 beta and this is part of Cosmic Super Key search bar.
And seems like broken since last friday update.

**Comment by xrazis** [comment]
Just did a fresh install of the beta and can confirm this behavior.

**Comment by blakeridgway** [comment]
If you are talking about the "search" feature that GNOME has - this is different than the Pop Shell launcher that is tied with Super key on default in 21.04.

**Comment by nigurr** [comment]
> If you are talking about the "search" feature that GNOME has - this is different than the Pop Shell launcher that is tied with Super key on default in 21.04.

it's about pop os shell launcher - https://www.reddit.com/r/pop_os/comments/o4kuig/search_bar_no_longer_suggesting_user_apps/

This is broken in latest pop os update and was working fine.

**Comment by blakeridgway** [comment]
> > If you are talking about the "search" feature that GNOME has - this is different than the Pop Shell launcher that is tied with Super key on default in 21.04.
> 
> it's about pop os shell launcher - https://www.reddit.com/r/pop_os/comments/o4kuig/search_bar_no_longer_suggesting_user_apps/
> 
> This is broken in latest pop os update and was working fine.

I misunderstood the issue. But I feel this is more adequte to post in Pop-Shell rather than COSMIC as they are two separate things.

It does appear to be in the process of being fixed if I understand [Shell #1018](https://github.com/pop-os/shell/pull/1018) properly.

**Comment by blakeridgway** [comment]
I confirmed this is working with this version of Pop Shell

`Installed: 1.1.0~1624306081~21.04~47d4829`

Update your system and see if it works for you now :)

**Comment by nigurr** [comment]
It's fixed
