### ISSUE TITLE
Bizzare tearing/doubling bug while switching from Applications to Workspaces

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/gnome-shell-extension-pop-cosmic#86]
A screenshot shows a nearly blank screen, so this photo will have to suffice. After performing steps listed bellow this issue occurs:
![20210623_160846_HDR](https://user-images.githubusercontent.com/63356574/123112408-f6953800-d43d-11eb-8ce5-e1f61cd8bc94.jpg)

Steps to reproduce:
1. Click on Applications or use a shortcut to open the application menu
2. Click on Workspaces 
3. If done in reverse no issue occurs, even while constantly switching. The issue seems contingent on opening the Applications menu first.
4. It doesn't matter how workspace picker is placed, issue occurs regardless.

Extensions:
![image](https://user-images.githubusercontent.com/63356574/123113615-f9445d00-d43e-11eb-8246-f3fe68a547c4.png)
Desktop settings:
![image](https://user-images.githubusercontent.com/63356574/123113883-301a7300-d43f-11eb-9cea-0ad7bf508ba6.png)
![image](https://user-images.githubusercontent.com/63356574/123113988-4294ac80-d43f-11eb-812b-68d675411bbf.png)

**Comment by DuttaAB-dev** [comment]
Can confirm this in my system aswell. But notably, clicking on workspaces, then applcations and then back to workspaces in that exact order does not trigger this issue.

**Comment by bflanagin** [comment]
Can confirm except that the issue requires the use of the top bar's Workspaces option. The hot corner, shortcut keys and icons in the dash aren't causing the issue. Can either of you confirm it requires the use of that particular button?

**Comment by Kartonrealista** [comment]
@bflanagin I have set super key action to open Workspaces (as you can see in the screenshot) in display settings. By using Super + A to open Applications and super to open Workspaces I get the same bug. Any combination of shortcuts and top bar's buttons results in the same bug.
Additionally if you have a window open it will bug out too, and if you try to move it with a mouse it leaves traces. 

Using "show workspaces" from the dock actually causes a different issue, as in it closes Applications but doesn't open Workspaces (you have to click it again). It doesn't cause the original issue though.

Video of the second issue:
https://user-images.githubusercontent.com/63356574/123158960-b600e300-d46c-11eb-8d67-f4f8d0f59a01.mp4

**Comment by ids1024** [comment]
The seems to happen with https://github.com/pop-os/cosmic/commit/fc0a4781e6b746b68d13ce9465c2d8f504899e3a but not with the previous commit. Not sure why...

Edit: Specifically the line `background.opacity = 0;`. Though that doesn't make too much sense.
Edit 2: Okay, I guess I see what the issue is, if not a better solution.
