### ISSUE TITLE
App grid showing behind Workspaces overview

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-shell-extension-pop-cosmic#92]
I'm assuming this was caused by https://github.com/pop-os/cosmic/pull/90.

On 702d7da, there's a case where the Applications grid shows up behind the window spread in the Workspaces overview:

![Screenshot from 2021-06-25 09-36-52](https://user-images.githubusercontent.com/7199422/123449447-ecd41780-d598-11eb-911e-25ef5c829ee2.png)

This happens after opening and closing the Applications menu by clicking the icon in the dock twice, then opening the Workspaces menu. It stops happening after navigating from the Applications menu to the Workspaces menu by clicking the menu item in the top left of the screen.

I've also had a case where Workspaces view didn't show my windows:

![rect839](https://user-images.githubusercontent.com/7199422/123450638-2eb18d80-d59a-11eb-86b7-5fa0b3430175.png)

I haven't been able to recreate this one yet, but I'm assuming they're both related to GNOME Shell not knowing which page is supposed to be active.

**Comment by WatchMkr** [comment]
I'm able to reproduce reliably with `Super + A` followed by `Super + D` directly after login.
![Screenshot from 2021-06-25 10-01-08](https://user-images.githubusercontent.com/3430283/123453379-b1d3e300-d59c-11eb-989d-e456142e7ca4.png)

**Comment by leviport** [comment]
I did a fresh install on a lemp9 and didn't see this happen until I added `master`. Whatever the cause is, I think it's still in staging.

**Comment by ids1024** [comment]
> Whatever the cause is, I think it's still in staging.

Almost certainly https://github.com/pop-os/cosmic/pull/90 as  @jacobgkau suggested. So reverting that would fix it, though maybe there's a better solution.
