### ISSUE TITLE
Visual glitches with app grid using alternate shell theme

### ISSUE THREAD

**Issue by ids1024** [pop-os/gnome-shell-extension-pop-cosmic#96]
Someone on Mattermost seems to have had this issue. Also appears with `yaru-theme-gnome-shell`, so probably any alternate shell theme.

This happens because Cosmic hides the background (https://github.com/pop-os/cosmic/pull/89), but relies on the shell theme to add an opaque background.

Perhaps Cosmic could not call `.hide()` on the background but instead add a css class, so the theme could set it invisible. Otherwise Cosmic should set an opaque background itself without relying on the theme.

**Comment by DuttaAB-dev** [comment]
Happens in my case while using adwaita gnome shell theme.
